In [1]:
import numpy as np
import pandas

import markov_chains_methods as mc
import utils as ul
import pandas as pd
import metrics
from time import time

In [2]:
df_1k_ranking=pandas.read_csv('rn_100_n_1k.csv')
df_1k_attribute=pandas.read_csv('1k_attribute.csv')
df_1k_attribute[df_1k_attribute['protected attribute']==-1]=0
df_1k_ranking,df_1k_attribute

(    Unnamed: 0    0    1    2    3    4    5    6    7     8  ...    990  \
 0            0  1.0  0.0  2.0  4.0  6.0  8.0  3.0  7.0   5.0  ...  986.0   
 1            1  0.0  1.0  3.0  2.0  5.0  7.0  6.0  8.0   9.0  ...  989.0   
 2            2  1.0  0.0  2.0  3.0  4.0  5.0  6.0  9.0   7.0  ...  991.0   
 3            3  2.0  1.0  0.0  4.0  3.0  5.0  7.0  6.0   8.0  ...  990.0   
 4            4  2.0  3.0  7.0  0.0  8.0  1.0  4.0  5.0   9.0  ...  989.0   
 ..         ...  ...  ...  ...  ...  ...  ...  ...  ...   ...  ...    ...   
 95          95  2.0  0.0  1.0  3.0  4.0  5.0  6.0  7.0  10.0  ...  989.0   
 96          96  0.0  1.0  2.0  3.0  4.0  5.0  7.0  6.0   9.0  ...  991.0   
 97          97  1.0  3.0  0.0  2.0  4.0  5.0  7.0  6.0   9.0  ...  989.0   
 98          98  1.0  0.0  2.0  5.0  4.0  7.0  3.0  6.0   8.0  ...  988.0   
 99          99  2.0  0.0  1.0  5.0  3.0  6.0  4.0  7.0   9.0  ...  989.0   
 
       991    992    993    994    995    996    997    998    999  
 0   

In [7]:
rankings = df_1k_ranking[df_1k_ranking.columns[1:]].to_numpy()
attribute=df_1k_attribute['protected attribute'].to_numpy()
attribute=np.c_[np.arange(rankings.shape[1]),attribute]
groups=df_1k_attribute.groupby(df_1k_attribute.columns[1]).count()
groups=groups.to_numpy()
groups=np.c_[np.array([[0],[1]]),groups]
rankings[:,250],rankings[:,251]=(rankings[:,251]).copy(),rankings[:,250].copy()
rankings[:,0],rankings[:,1]=(rankings[:,1]).copy(),rankings[:,0].copy()
rankings[:,250],attribute,groups

(array([251., 250., 249., 255., 250., 251., 247., 252., 251., 250., 251.,
        250., 251., 248., 249., 251., 252., 251., 254., 251., 252., 244.,
        250., 251., 252., 251., 251., 252., 251., 251., 252., 250., 250.,
        251., 252., 251., 252., 251., 253., 250., 251., 251., 252., 251.,
        251., 251., 250., 252., 252., 249., 250., 251., 250., 249., 251.,
        254., 256., 250., 251., 251., 244., 251., 251., 255., 256., 252.,
        253., 250., 250., 252., 254., 251., 251., 250., 252., 252., 249.,
        252., 252., 252., 253., 251., 251., 248., 253., 248., 251., 251.,
        251., 250., 251., 252., 251., 252., 251., 250., 251., 250., 249.,
        253.]),
 array([[  0,   1],
        [  1,   0],
        [  2,   0],
        ...,
        [997,   0],
        [998,   0],
        [999,   0]], dtype=int64),
 array([[  0, 500],
        [  1, 500]], dtype=int64))

In [8]:
threshold=0
rankings.shape

(100, 1000)

In [9]:
t0=time()
agg_ranking_0=mc.aggregate_rank_mc(rankings,0)
t1=time()
print(t1-t0)
t0=time()
agg_ranking_1=mc.aggregate_rank_mc(rankings,1)
t1=time()
print(t1-t0)
agg_ranking_0,t1-t0,agg_ranking_1

[  0.  40.  77.  85.  95.  98.  99. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 

(array([998, 999, 997, 996, 995, 994, 993, 992, 991, 990, 989, 988, 987,
        986, 985, 984, 983, 982, 981, 980, 979, 978, 977, 976, 975, 974,
        973, 972, 971, 970, 969, 968, 967, 966, 965, 964, 963, 962, 961,
        960, 959, 958, 957, 956, 955, 954, 953, 952, 951, 950, 949, 948,
        947, 946, 945, 944, 943, 942, 941, 940, 939, 938, 937, 936, 935,
        934, 933, 932, 931, 930, 929, 928, 927, 926, 925, 924, 923, 922,
        921, 920, 919, 918, 917, 916, 915, 914, 913, 912, 911, 910, 909,
        908, 907, 906, 905, 904, 903, 902, 901, 900, 899, 898, 897, 896,
        895, 894, 893, 892, 891, 890, 889, 888, 887, 886, 885, 884, 883,
        882, 881, 880, 879, 878, 877, 876, 875, 874, 873, 872, 871, 870,
        869, 868, 867, 866, 865, 864, 863, 862, 861, 860, 859, 858, 857,
        856, 855, 854, 853, 852, 851, 850, 849, 848, 847, 846, 845, 844,
        843, 842, 841, 840, 839, 838, 837, 836, 835, 834, 833, 832, 831,
        830, 829, 828, 827, 826, 825, 824, 823, 822

In [6]:
agg_ranking_permutation_0=np.argsort(agg_ranking_0)
agg_ranking_permutation_1=np.argsort(agg_ranking_1)
agg_ranking_permutation_0,agg_ranking_permutation_1,ul.kemeny_dist(rankings,agg_ranking_0),ul.kemeny_dist(rankings,agg_ranking_1)

(array([999, 998, 997, 996, 995, 994, 993, 992, 991, 990, 989, 988, 987,
        986, 985, 984, 983, 982, 981, 980, 979, 978, 977, 976, 975, 974,
        973, 972, 971, 970, 969, 968, 967, 966, 965, 964, 963, 962, 961,
        960, 959, 958, 957, 956, 955, 954, 953, 952, 951, 950, 949, 948,
        947, 946, 945, 944, 943, 942, 941, 940, 939, 938, 937, 936, 935,
        934, 933, 932, 931, 930, 929, 928, 927, 926, 925, 924, 923, 922,
        921, 920, 919, 918, 917, 916, 915, 914, 913, 912, 911, 910, 909,
        908, 907, 906, 905, 904, 903, 902, 901, 900, 899, 898, 897, 896,
        895, 894, 893, 892, 891, 890, 889, 888, 887, 886, 885, 884, 883,
        882, 881, 880, 879, 878, 877, 876, 875, 874, 873, 872, 871, 870,
        869, 868, 867, 866, 865, 864, 863, 862, 861, 860, 859, 858, 857,
        856, 855, 854, 853, 852, 851, 850, 849, 848, 847, 846, 845, 844,
        843, 842, 841, 840, 839, 838, 837, 836, 835, 834, 833, 832, 831,
        830, 829, 828, 827, 826, 825, 824, 823, 822

In [8]:
fair_agg_ranking_permutation_1=ul.GrBinaryIPF(agg_ranking_permutation_1,attribute[:,1])
fair_agg_ranking_1=np.zeros(len(fair_agg_ranking_permutation_1))
for i in range(len(fair_agg_ranking_permutation_1)):
    fair_agg_ranking_1[fair_agg_ranking_permutation_1[i]]=i
fair_agg_ranking_permutation_1,fair_agg_ranking_1

[]
[0]
[0, 1]
[0, 1, 2]
[0, 1, 2, 3]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4, 5]
[0, 1, 2, 3, 4, 5, 6]
[0, 1, 2, 3, 4, 5, 6, 9]
[0, 1, 2, 3, 4, 5, 6, 9, 7]
[0, 1, 2, 3, 4, 5, 6, 9, 7, 11]
[0, 1, 2, 3, 4, 5, 6, 9, 7, 11, 8]
[0, 1, 2, 3, 4, 5, 6, 9, 7, 11, 8, 14]
[0, 1, 2, 3, 4, 5, 6, 9, 7, 11, 8, 14, 10]
[0, 1, 2, 3, 4, 5, 6, 9, 7, 11, 8, 14, 10, 18]
[0, 1, 2, 3, 4, 5, 6, 9, 7, 11, 8, 14, 10, 18, 12]
[0, 1, 2, 3, 4, 5, 6, 9, 7, 11, 8, 14, 10, 18, 12, 21]
[0, 1, 2, 3, 4, 5, 6, 9, 7, 11, 8, 14, 10, 18, 12, 21, 13]
[0, 1, 2, 3, 4, 5, 6, 9, 7, 11, 8, 14, 10, 18, 12, 21, 13, 23]
[0, 1, 2, 3, 4, 5, 6, 9, 7, 11, 8, 14, 10, 18, 12, 21, 13, 23, 15]
[0, 1, 2, 3, 4, 5, 6, 9, 7, 11, 8, 14, 10, 18, 12, 21, 13, 23, 15, 24]
[0, 1, 2, 3, 4, 5, 6, 9, 7, 11, 8, 14, 10, 18, 12, 21, 13, 23, 15, 24, 16]
[0, 1, 2, 3, 4, 5, 6, 9, 7, 11, 8, 14, 10, 18, 12, 21, 13, 23, 15, 24, 16, 28]
[0, 1, 2, 3, 4, 5, 6, 9, 7, 11, 8, 14, 10, 18, 12, 21, 13, 23, 15, 24, 16, 28, 17]
[0, 1, 2, 3, 4, 5, 6, 9, 7, 11, 8, 14, 10, 18, 12, 21,

([0,
  1,
  2,
  3,
  4,
  5,
  6,
  9,
  7,
  11,
  8,
  14,
  10,
  18,
  12,
  21,
  13,
  23,
  15,
  24,
  16,
  28,
  17,
  31,
  19,
  33,
  20,
  37,
  22,
  42,
  25,
  43,
  26,
  44,
  27,
  51,
  29,
  55,
  30,
  58,
  32,
  60,
  34,
  62,
  35,
  63,
  36,
  66,
  38,
  69,
  39,
  73,
  40,
  74,
  41,
  77,
  45,
  79,
  46,
  82,
  47,
  91,
  48,
  105,
  49,
  107,
  50,
  111,
  52,
  117,
  53,
  118,
  54,
  123,
  56,
  140,
  57,
  141,
  59,
  142,
  61,
  147,
  64,
  154,
  65,
  155,
  67,
  160,
  68,
  164,
  70,
  165,
  71,
  169,
  72,
  170,
  75,
  175,
  76,
  182,
  78,
  183,
  80,
  186,
  81,
  190,
  83,
  192,
  84,
  193,
  85,
  195,
  86,
  197,
  87,
  199,
  88,
  200,
  89,
  203,
  90,
  212,
  92,
  213,
  93,
  217,
  94,
  218,
  95,
  219,
  96,
  221,
  97,
  222,
  98,
  223,
  99,
  225,
  100,
  227,
  101,
  228,
  102,
  231,
  103,
  238,
  104,
  239,
  106,
  249,
  108,
  250,
  109,
  256,
  110,
  260,
  112,
  261,
  11

In [7]:
fair_agg_ranking_distance_1=ul.kemeny_dist(rankings,fair_agg_ranking_1)
fair_agg_ranking_distance_1

NameError: name 'fair_agg_ranking_1' is not defined

In [5]:
fair_kemeny_rankings_greedy_0_t0=time()
fair_kemeny_rankings_greedy_0=mc.fair_kemeny_mc_rankings_greedy(rankings,attribute,groups,threshold,0)
fair_kemeny_rankings_greedy_0_t1=time()
fair_kemeny_rankings_greedy_0_t1-fair_kemeny_rankings_greedy_0_t0

initial: 0


13.396073341369629

In [11]:
fair_kemeny_rankings_greedy_0

[(array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   8.,  10.,   7.,  12.,
           9.,  14.,  16.,  11.,  18.,  20.,  22.,  13.,  24.,  26.,  15.,
          28.,  17.,  19.,  30.,  32.,  34.,  21.,  36.,  38.,  23.,  40.,
          25.,  42.,  44.,  46.,  27.,  48.,  50.,  52.,  54.,  29.,  31.,
          33.,  56.,  58.,  60.,  62.,  64.,  66.,  35.,  68.,  70.,  72.,
          37.,  74.,  76.,  39.,  78.,  41.,  80.,  43.,  45.,  82.,  84.,
          47.,  86.,  88.,  49.,  90.,  92.,  94.,  51.,  53.,  96.,  98.,
          55., 100.,  57., 102., 104.,  59., 106., 108., 110., 112., 114.,
         116., 118., 120.,  61., 122., 124., 126., 128., 130., 132., 134.,
         136., 138., 140., 142., 144., 146.,  63., 148.,  65., 150., 152.,
         154.,  67., 156., 158., 160., 162., 164.,  69.,  71., 166., 168.,
         170., 172.,  73., 174., 176., 178., 180., 182., 184., 186., 188.,
         190., 192., 194., 196., 198., 200., 202., 204.,  75.,  77.,  79.,
         206., 208., 210.