In [1]:
import numpy as np
import markov_chains_methods as mc
import utils as ul
import pandas as pd
import metrics
from time import time

In [7]:
base_ranks = np.load('cs_baseranks.npy').astype(int)
base_ranks


array([[ 0,  1, 11, ..., 61, 56, 49],
       [ 0,  3,  1, ..., 60, 52, 61],
       [ 0,  3,  5, ..., 43, 49, 52],
       ...,
       [ 0,  2,  8, ..., 52, 61, 53],
       [ 0,  1,  4, ..., 63, 52, 61],
       [ 0,  2,  1, ..., 61, 62, 53]])

In [30]:
for i in range(0):
    print('a')

In [26]:
from random import randrange

a=np.empty(0)
b=np.arange(10)
c=np.arange(10,15)
print(np.array([43]),a,b)
#d=np.concatenate((b,a,np.array([17]),c))
d=np.concatenate((a,np.array([70]),a))
a,b,c,d

[43] [] [0 1 2 3 4 5 6 7 8 9]


(array([], dtype=float64),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14]),
 array([70.]))

In [ ]:
rankings =base_ranks