In [1]:
import numpy as np
import markov_chains_methods as mc
import utils as ul
import pandas as pd
import metrics
from time import time

In [7]:
base_ranks = np.load('cs_baseranks.npy').astype(int)
base_ranks

array([[ 0,  1, 11, ..., 61, 56, 49],
       [ 0,  3,  1, ..., 60, 52, 61],
       [ 0,  3,  5, ..., 43, 49, 52],
       ...,
       [ 0,  2,  8, ..., 52, 61, 53],
       [ 0,  1,  4, ..., 63, 52, 61],
       [ 0,  2,  1, ..., 61, 62, 53]])

In [39]:
cs_groups_df=pd.read_csv('cs_groups.csv', header=None,names=['candidate','attr_1','attr_2'])
cs_groups_df=cs_groups_df[['candidate','attr_2']]
attribute=cs_groups_df
groups=cs_groups_df.groupby(cs_groups_df.columns[1]).count()
groups=groups.to_numpy()
groups=np.c_[np.array([[0],[1]]),groups]
attribute,groups

(    candidate  attr_2
 0           0       0
 1           1       0
 2           2       1
 3           3       1
 4           4       0
 ..        ...     ...
 60         60       1
 61         61       1
 62         62       0
 63         63       1
 64         64       0
 
 [65 rows x 2 columns],
 array([[ 0, 26],
        [ 1, 39]], dtype=int64))

In [30]:
for i in range(0):
    print('a')

In [26]:
from random import randrange

a=np.empty(0)
b=np.arange(10)
c=np.arange(10,15)
print(np.array([43]),a,b)
#d=np.concatenate((b,a,np.array([17]),c))
d=np.concatenate((a,np.array([70]),a))
a,b,c,d

[43] [] [0 1 2 3 4 5 6 7 8 9]


(array([], dtype=float64),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14]),
 array([70.]))

In [ ]:
rankings =base_ranks