In [37]:
import numpy as np
import markov_chains_methods as mc
import utils as ul
import pandas as pd
import metrics
from time import time

In [38]:

df=pd.read_csv('20230918dataset_uf.csv')
#add a ranking all m candidates has smaller rank than w's
df["ranker 11"]=np.arange(1,101,1)
#add a ranking half  m candidates on the top of ranking and another half m candidates on the bottom of rinking and w candidates on the middle  
ranker_12=np.concatenate((np.arange(1,16,1),np.arange(86,101,1),np.arange(16,86,1)), axis=None)
#print(ranker_12)
df["ranker 12"]=ranker_12
df

Unnamed: 0  ranker 1  ranker 2  ranker 3  ranker 4  ranker 5  ranker 6  \
0         M01        20        86        79        32        28        70   
1         M02        14         9         7        52        55        26   
2         M03        22         3        24        31        97        29   
3         M04        54        87        13        22        95        46   
4         M05        93         6        53        92        31        10   
..        ...       ...       ...       ...       ...       ...       ...   
95        W66        44        29        85        15        72        11   
96        W67        50        66        29        83         4        81   
97        W68        65        75        78        80        68        12   
98        W69        41        60         9        34        99        30   
99        W70        70        43        19        38        29        35   

    ranker 7  ranker 8  ranker 9  ranker 10  ranker 11  ranker 12  
0         21        71        71         71          1          1  
1         89        72        72         72          2          2  
2         41        73        73         73          3          3  
3         32        74        74         74          4          4  
4         56        75        75         75          5          5  
..       ...       ...       ...        ...        ...        ...  
95        67        66        66         66         96         81  
96        40        67        67         67         97         82  
97        73        68        68         68         98         83  
98        63        69        69         69         99         84  
99        52        70        70         70        100         85  

[100 rows x 13 columns]

In [39]:
rankings=df[df.columns[1:]].to_numpy()
rankings

array([[ 20,  86,  79, ...,  71,   1,   1],
       [ 14,   9,   7, ...,  72,   2,   2],
       [ 22,   3,  24, ...,  73,   3,   3],
       ...,
       [ 65,  75,  78, ...,  68,  98,  83],
       [ 41,  60,   9, ...,  69,  99,  84],
       [ 70,  43,  19, ...,  70, 100,  85]], dtype=int64)

In [40]:
rankings=rankings.transpose()
rankings,rankings.shape

(array([[ 20,  14,  22, ...,  65,  41,  70],
        [ 86,   9,   3, ...,  75,  60,  43],
        [ 79,   7,  24, ...,  78,   9,  19],
        ...,
        [ 71,  72,  73, ...,  68,  69,  70],
        [  1,   2,   3, ...,  98,  99, 100],
        [  1,   2,   3, ...,  83,  84,  85]], dtype=int64),
 (12, 100))

In [41]:
threshold=0

In [42]:
attribute = np.append(np.repeat(0, 30), np.repeat(1, 70))
attribute=np.c_[np.arange(100),attribute]
df_groups=pd.DataFrame(attribute,columns=['id','attribute'])
groups=df_groups.groupby(df_groups.columns[1]).count()
groups=groups.to_numpy()
groups=np.c_[np.array([[0],[1]]),groups]
size_candidate = rankings.shape[1]

In [43]:
precedence=mc.build_precedence_matrix(rankings)
out_degree=mc.build_out_degree_matrix(precedence)
matrix=mc.incresing_consensus_transition_matrix(rankings,precedence,out_degree)
matrix[0]

array([0.50949167, 0.0061    , 0.0061    , 0.005225  , 0.00525   ,
       0.004875  , 0.00461667, 0.00505833, 0.00494167, 0.00501667,
       0.00570833, 0.00553333, 0.0052    , 0.00408333, 0.00489167,
       0.0036    , 0.00400833, 0.0036    , 0.00303333, 0.00335   ,
       0.00541667, 0.00410833, 0.00311667, 0.00411667, 0.004875  ,
       0.00353333, 0.00436667, 0.00301667, 0.00345   , 0.00428333,
       0.00700833, 0.00725   , 0.00604167, 0.005175  , 0.00651667,
       0.00539167, 0.0056    , 0.00553333, 0.00630833, 0.00551667,
       0.0066    , 0.004925  , 0.0065    , 0.00675   , 0.0064    ,
       0.00715   , 0.00664167, 0.00724167, 0.00631667, 0.00571667,
       0.00571667, 0.0056    , 0.006225  , 0.00575   , 0.00573333,
       0.006425  , 0.005125  , 0.00539167, 0.00581667, 0.004125  ,
       0.00620833, 0.00498333, 0.00531667, 0.00585   , 0.005175  ,
       0.004825  , 0.00516667, 0.004125  , 0.004325  , 0.00548333,
       0.005125  , 0.00328333, 0.0043    , 0.005275  , 0.00442

In [44]:
attribute

array([[ 0,  0],
       [ 1,  0],
       [ 2,  0],
       [ 3,  0],
       [ 4,  0],
       [ 5,  0],
       [ 6,  0],
       [ 7,  0],
       [ 8,  0],
       [ 9,  0],
       [10,  0],
       [11,  0],
       [12,  0],
       [13,  0],
       [14,  0],
       [15,  0],
       [16,  0],
       [17,  0],
       [18,  0],
       [19,  0],
       [20,  0],
       [21,  0],
       [22,  0],
       [23,  0],
       [24,  0],
       [25,  0],
       [26,  0],
       [27,  0],
       [28,  0],
       [29,  0],
       [30,  1],
       [31,  1],
       [32,  1],
       [33,  1],
       [34,  1],
       [35,  1],
       [36,  1],
       [37,  1],
       [38,  1],
       [39,  1],
       [40,  1],
       [41,  1],
       [42,  1],
       [43,  1],
       [44,  1],
       [45,  1],
       [46,  1],
       [47,  1],
       [48,  1],
       [49,  1],
       [50,  1],
       [51,  1],
       [52,  1],
       [53,  1],
       [54,  1],
       [55,  1],
       [56,  1],
       [57,  1],
       [58,  1

In [45]:
#fair_kemeny_rankings_greedy_1_t0=time()
#fair_kemeny_rankings_greedy_1=mc.fair_kemeny_mc_rankings_greedy(rankings,attribute,groups,threshold,1)
#fair_kemeny_rankings_greedy_1_t1=time()

fair_kemeny_rankings_greedy_0_t0=time()
fair_kemeny_rankings_greedy_0=mc.fair_kemeny_mc_rankings_greedy(rankings,attribute,groups,threshold,0)
fair_kemeny_rankings_greedy_0_t1=time()

#fair_kemeny_rankings_greedy_1_t1-fair_kemeny_rankings_greedy_1_t0,
fair_kemeny_rankings_greedy_0_t1-fair_kemeny_rankings_greedy_0_t0

initial: 47


0.13900160789489746

In [46]:
fair_kemeny_rankings_greedy_0

array([16., 21.,  3., 45., 19., 57., 49., 29., 36., 33.,  6.,  9., 26.,
       66., 39., 73., 69., 76., 93., 86., 13., 82., 89., 63., 43., 79.,
       53., 99., 95., 56.,  4.,  1., 22., 50., 12., 41., 32., 37., 20.,
       34.,  8., 54., 10.,  5., 14.,  2.,  7.,  0., 15., 30., 28., 31.,
       17., 25., 27., 11., 51., 38., 23., 85., 18., 52., 42., 24., 48.,
       55., 46., 83., 74., 35., 47., 96., 75., 44., 70., 67., 40., 68.,
       80., 84., 59., 60., 77., 92., 81., 91., 64., 97., 87., 61., 94.,
       71., 65., 58., 62., 78., 90., 98., 88., 72.])

In [47]:
fair_kemeny_rankings_greedy_0_dist=ul.kemeny_dist(rankings,fair_kemeny_rankings_greedy_0)
fair_kemeny_ranking_greedy_0_permutation=np.argsort(fair_kemeny_rankings_greedy_0)
fair_kemeny_ranking_greedy_0_permutation,fair_kemeny_rankings_greedy_0_dist

(array([47, 31, 45,  2, 30, 43, 10, 46, 40, 11, 42, 55, 34, 20, 44, 48,  0,
        52, 60,  4, 38,  1, 32, 58, 63, 53, 12, 54, 50,  7, 49, 51, 36,  9,
        39, 69,  8, 37, 57, 14, 76, 35, 62, 24, 73,  3, 66, 70, 64,  6, 33,
        56, 61, 26, 41, 65, 29,  5, 93, 80, 81, 89, 94, 23, 86, 92, 13, 75,
        77, 16, 74, 91, 99, 15, 68, 72, 17, 82, 95, 25, 78, 84, 21, 67, 79,
        59, 19, 88, 98, 22, 96, 85, 83, 18, 90, 28, 71, 87, 97, 27],
       dtype=int64),
 22614)

In [48]:
fair_kemeny_ranking_greedy_0_m=np.c_[np.arange(30),fair_kemeny_rankings_greedy_0[:30]]
fair_kemeny_ranking_greedy_0_w=np.c_[np.arange(30,100),fair_kemeny_rankings_greedy_0[30:]]
parity_optimal_fair_kemeny_ranking_greedy_0=metrics.pairwise_statistical_parity(fair_kemeny_ranking_greedy_0_m,fair_kemeny_ranking_greedy_0_w)
parity_optimal_fair_kemeny_ranking_greedy_0

-0.03619047619047619

In [49]:
satisfied_array=[]
k_threshold=0.05
for k in range(1,100):
    ranking =pd.DataFrame(columns=['id', 'ranker'])
    ranking["id"]=np.arange(0,100,1)
    ranking["ranker"]=fair_kemeny_rankings_greedy_0
    ranking_m =ranking.head(30).to_numpy()
    ranking_w =ranking.tail(70).to_numpy()
    rankings_fair=np.array([ranking_m,ranking_w], dtype=object)
    satisfied=metrics.top_k_parity(rankings_fair,k,k-threshold )
    satisfied_array.append(["ranker",k,satisfied])

In [50]:
satisfied_array=np.array(satisfied_array)
satisfied_array

array([['ranker', '1', 'True'],
       ['ranker', '2', 'True'],
       ['ranker', '3', 'True'],
       ['ranker', '4', 'True'],
       ['ranker', '5', 'True'],
       ['ranker', '6', 'True'],
       ['ranker', '7', 'True'],
       ['ranker', '8', 'True'],
       ['ranker', '9', 'True'],
       ['ranker', '10', 'True'],
       ['ranker', '11', 'True'],
       ['ranker', '12', 'True'],
       ['ranker', '13', 'True'],
       ['ranker', '14', 'True'],
       ['ranker', '15', 'True'],
       ['ranker', '16', 'True'],
       ['ranker', '17', 'True'],
       ['ranker', '18', 'True'],
       ['ranker', '19', 'True'],
       ['ranker', '20', 'True'],
       ['ranker', '21', 'True'],
       ['ranker', '22', 'True'],
       ['ranker', '23', 'True'],
       ['ranker', '24', 'True'],
       ['ranker', '25', 'True'],
       ['ranker', '26', 'True'],
       ['ranker', '27', 'True'],
       ['ranker', '28', 'True'],
       ['ranker', '29', 'True'],
       ['ranker', '30', 'True'],
       ['ranker', '

In [51]:
satisfied_array=np.array(satisfied_array)
satisfied_array

array([['ranker', '1', 'True'],
       ['ranker', '2', 'True'],
       ['ranker', '3', 'True'],
       ['ranker', '4', 'True'],
       ['ranker', '5', 'True'],
       ['ranker', '6', 'True'],
       ['ranker', '7', 'True'],
       ['ranker', '8', 'True'],
       ['ranker', '9', 'True'],
       ['ranker', '10', 'True'],
       ['ranker', '11', 'True'],
       ['ranker', '12', 'True'],
       ['ranker', '13', 'True'],
       ['ranker', '14', 'True'],
       ['ranker', '15', 'True'],
       ['ranker', '16', 'True'],
       ['ranker', '17', 'True'],
       ['ranker', '18', 'True'],
       ['ranker', '19', 'True'],
       ['ranker', '20', 'True'],
       ['ranker', '21', 'True'],
       ['ranker', '22', 'True'],
       ['ranker', '23', 'True'],
       ['ranker', '24', 'True'],
       ['ranker', '25', 'True'],
       ['ranker', '26', 'True'],
       ['ranker', '27', 'True'],
       ['ranker', '28', 'True'],
       ['ranker', '29', 'True'],
       ['ranker', '30', 'True'],
       ['ranker', '

In [52]:

t0=time()
agg_ranking_0=mc.aggregate_rank_mc(rankings,0)
t1=time()
agg_ranking_1=mc.aggregate_rank_mc(rankings,1)
agg_ranking_0,t1-t0,agg_ranking_1

[ 0.  8.  8.  9.  9.  9.  9.  8.  8.  9.  7.  8.  8.  9.  8.  8.  8.  9.
 10.  9.  6.  8. 11.  9.  8.  8.  6. 10.  9.  8.  6.  4.  6.  8.  6.  8.
  7.  7.  8.  6.  6.  8.  5.  6.  4.  3.  5.  3.  5.  7.  6.  6.  5.  5.
  6.  4.  6.  6.  5.  8.  4.  6.  6.  6.  6.  6.  4.  6.  6.  4.  5.  8.
  6.  5.  6.  7.  5.  6.  6.  7.  6.  5.  6.  6.  5.  6.  6.  6.  6.  5.
  7.  6.  4.  5.  6.  6.  6.  6.  6.  6.]
[649. 728. 728. 621. 624. 579. 548. 603. 589. 596. 683. 660. 620. 484.
 583. 428. 477. 426. 356. 396. 650. 489. 364. 488. 581. 420. 524. 354.
 408. 510. 841. 874. 725. 617. 782. 643. 670. 662. 753. 662. 792. 587.
 782. 810. 772. 864. 799. 875. 760. 684. 686. 672. 749. 692. 688. 775.
 615. 647. 700. 491. 749. 598. 638. 702. 621. 579. 624. 495. 519. 662.
 617. 390. 516. 635. 531. 536. 637. 536. 505. 493. 563. 567. 510. 459.
 496. 463. 553. 373. 486. 560. 435. 524. 548. 570. 549. 502. 467. 364.
 474. 519.]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
3

(array([31, 16, 17, 38, 34, 52, 58, 42, 48, 45, 18, 28, 39, 77, 51, 90, 80,
        89, 98, 93, 29, 72, 94, 74, 49, 88, 63, 95, 92, 64,  3,  0, 14, 37,
         7, 32, 22, 27, 11, 26,  5, 50,  8,  4,  9,  2,  6,  1, 12, 25, 23,
        30, 13, 21, 24, 10, 47, 35, 20, 84, 15, 53, 40, 19, 46, 55, 43, 83,
        71, 33, 44, 97, 73, 41, 69, 66, 36, 65, 76, 79, 59, 57, 75, 86, 78,
        87, 62, 96, 81, 56, 91, 67, 61, 54, 60, 70, 85, 99, 82, 68],
       dtype=int64),
 0.14099740982055664,
 array([32, 16, 15, 41, 39, 54, 62, 46, 49, 48, 24, 30, 42, 82, 51, 89, 83,
        90, 98, 93, 31, 79, 97, 80, 52, 91, 67, 99, 92, 72,  3,  1, 17, 44,
         8, 34, 26, 29, 12, 28,  6, 50,  7,  4, 10,  2,  5,  0, 11, 23, 22,
        25, 14, 20, 21,  9, 45, 33, 19, 78, 13, 47, 35, 18, 40, 53, 38, 76,
        68, 27, 43, 94, 70, 37, 65, 63, 36, 64, 73, 77, 57, 56, 71, 87, 75,
        86, 59, 95, 81, 58, 88, 66, 61, 55, 60, 74, 85, 96, 84, 69],
       dtype=int64))

In [53]:
agg_ranking_permutation_0=np.argsort(agg_ranking_0)
agg_ranking_permutation_1=np.argsort(agg_ranking_1)
agg_ranking_permutation_0,agg_ranking_permutation_1,ul.kemeny_dist(rankings,agg_ranking_0),ul.kemeny_dist(rankings,agg_ranking_1)

(array([31, 47, 45, 30, 43, 40, 46, 34, 42, 44, 55, 38, 48, 52, 32, 60,  1,
         2, 10, 63, 58, 53, 36, 50, 54, 49, 39, 37, 11, 20, 51,  0, 35, 69,
         4, 57, 76, 33,  3, 12, 62, 73,  7, 66, 70,  9, 64, 56,  8, 24, 41,
        14,  5, 61, 93, 65, 89, 81,  6, 80, 94, 92, 86, 26, 29, 77, 75, 91,
        99, 74, 95, 68, 21, 72, 23, 82, 78, 13, 84, 79, 16, 88, 98, 67, 59,
        96, 83, 85, 25, 17, 15, 90, 28, 19, 22, 27, 87, 71, 18, 97],
       dtype=int64),
 array([47, 31, 45, 30, 43, 46, 40, 42, 34, 55, 44, 48, 38, 60, 52,  2,  1,
        32, 63, 58, 53, 54, 50, 49, 10, 51, 36, 69, 39, 37, 11, 20,  0, 57,
        35, 62, 76, 73, 66,  4, 64,  3, 12, 70, 33, 56,  7, 61,  9,  8, 41,
        14, 24, 65,  5, 93, 81, 80, 89, 86, 94, 92,  6, 75, 77, 74, 91, 26,
        68, 99, 72, 82, 29, 78, 95, 84, 67, 79, 59, 21, 23, 88, 13, 16, 98,
        96, 85, 83, 90, 15, 17, 25, 28, 19, 71, 87, 97, 22, 18, 27],
       dtype=int64),
 22318,
 22224)

In [54]:
fair_agg_ranking_permutation_0=ul.GrBinaryIPF(agg_ranking_permutation_0,attribute[:,1])
fair_agg_ranking_0=np.zeros(len(fair_agg_ranking_permutation_0))
for i in range(len(fair_agg_ranking_permutation_0)):
    fair_agg_ranking_0[fair_agg_ranking_permutation_0[i]]=i
fair_agg_ranking_permutation_0,fair_agg_ranking_0

([31,
  47,
  45,
  1,
  30,
  43,
  2,
  40,
  46,
  10,
  34,
  42,
  44,
  11,
  55,
  38,
  20,
  48,
  52,
  0,
  32,
  60,
  63,
  4,
  58,
  53,
  3,
  36,
  50,
  12,
  54,
  49,
  39,
  7,
  37,
  51,
  9,
  35,
  69,
  8,
  57,
  76,
  33,
  24,
  62,
  73,
  14,
  66,
  70,
  5,
  64,
  56,
  41,
  6,
  61,
  93,
  26,
  65,
  89,
  29,
  81,
  80,
  94,
  21,
  92,
  86,
  23,
  77,
  75,
  13,
  91,
  99,
  74,
  16,
  95,
  68,
  25,
  72,
  82,
  17,
  78,
  84,
  79,
  15,
  88,
  98,
  28,
  67,
  59,
  19,
  96,
  83,
  85,
  22,
  90,
  27,
  87,
  71,
  18,
  97],
 array([19.,  3.,  6., 26., 23., 49., 53., 33., 39., 36.,  9., 13., 29.,
        69., 46., 83., 73., 79., 98., 89., 16., 63., 93., 66., 43., 76.,
        56., 95., 86., 59.,  4.,  0., 20., 42., 10., 37., 27., 34., 15.,
        32.,  7., 52., 11.,  5., 12.,  2.,  8.,  1., 17., 31., 28., 35.,
        18., 25., 30., 14., 51., 40., 24., 88., 21., 54., 44., 22., 50.,
        57., 47., 87., 75., 38., 48., 97., 7

In [55]:
fair_agg_ranking_permutation_1=ul.GrBinaryIPF(agg_ranking_permutation_1,attribute[:,1])
fair_agg_ranking_1=np.zeros(len(fair_agg_ranking_permutation_1))
for i in range(len(fair_agg_ranking_permutation_1)):
    fair_agg_ranking_1[fair_agg_ranking_permutation_1[i]]=i
fair_agg_ranking_permutation_1,fair_agg_ranking_1

([47,
  31,
  45,
  2,
  30,
  43,
  1,
  46,
  40,
  10,
  42,
  34,
  55,
  11,
  44,
  48,
  20,
  38,
  60,
  0,
  52,
  32,
  63,
  4,
  58,
  53,
  3,
  54,
  50,
  12,
  49,
  51,
  36,
  7,
  69,
  39,
  9,
  37,
  57,
  8,
  35,
  62,
  76,
  14,
  73,
  66,
  24,
  64,
  70,
  5,
  33,
  56,
  61,
  6,
  41,
  65,
  26,
  93,
  81,
  29,
  80,
  89,
  86,
  21,
  94,
  92,
  23,
  75,
  77,
  13,
  74,
  91,
  68,
  16,
  99,
  72,
  15,
  82,
  78,
  17,
  95,
  84,
  67,
  25,
  79,
  59,
  28,
  88,
  98,
  19,
  96,
  85,
  83,
  22,
  90,
  71,
  18,
  87,
  97,
  27],
 array([19.,  6.,  3., 26., 23., 49., 53., 33., 39., 36.,  9., 13., 29.,
        69., 43., 76., 73., 79., 96., 89., 16., 63., 93., 66., 46., 83.,
        56., 99., 86., 59.,  4.,  1., 21., 50., 11., 40., 32., 37., 17.,
        35.,  8., 54., 10.,  5., 14.,  2.,  7.,  0., 15., 30., 28., 31.,
        20., 25., 27., 12., 51., 38., 24., 85., 18., 52., 41., 22., 47.,
        55., 45., 82., 72., 34., 48., 95., 7

In [56]:
fair_agg_ranking_distance_0=ul.kemeny_dist(rankings,fair_agg_ranking_0)
fair_agg_ranking_distance_0

22546

In [57]:
fair_agg_ranking_distance_1=ul.kemeny_dist(rankings,fair_agg_ranking_1)
fair_agg_ranking_distance_1

22544

In [58]:
fair_agg_ranking_0_m=np.c_[np.arange(30),fair_agg_ranking_0[:30]]
fair_agg_ranking_0_w=np.c_[np.arange(30,100),fair_agg_ranking_0[30:]]
parity_fair_agg_ranking_0=metrics.pairwise_statistical_parity(fair_agg_ranking_0_m,fair_agg_ranking_0_w)
parity_fair_agg_ranking_0

-0.040952380952380955

In [59]:
fair_agg_ranking_1_m=np.c_[np.arange(30),fair_agg_ranking_1[:30]]
fair_agg_ranking_1_w=np.c_[np.arange(30,100),fair_agg_ranking_1[30:]]
parity_fair_agg_ranking_1=metrics.pairwise_statistical_parity(fair_agg_ranking_1_m,fair_agg_ranking_1_w)
parity_fair_agg_ranking_1

-0.04285714285714286

In [60]:
agg_ranking_0_satisfied_array=[]
k_threshold=threshold
for k in range(1,100):
    agg_ranking_0_k =pd.DataFrame(columns=['id', 'ranker'])
    agg_ranking_0_k["id"]=np.arange(0,100,1)
    agg_ranking_0_k["ranker"]=agg_ranking_0
    agg_ranking_0_k_m =agg_ranking_0_k.head(30).to_numpy()
    agg_ranking_0_k_w =agg_ranking_0_k.tail(70).to_numpy()
    agg_ranking_0_k_groups=np.array([agg_ranking_0_k_m,agg_ranking_0_k_w], dtype=object)
    agg_ranking_0_k_satisfied=metrics.top_k_parity(agg_ranking_0_k_groups,k,k_threshold )
    print(["ranker",k,agg_ranking_0_k_satisfied])
    agg_ranking_0_satisfied_array.append(["ranker",k,agg_ranking_0_k_satisfied])


['ranker', 1, True]
['ranker', 2, True]
['ranker', 3, True]
['ranker', 4, False]
['ranker', 5, False]
['ranker', 6, False]
['ranker', 7, False]
['ranker', 8, False]
['ranker', 9, False]
['ranker', 10, False]
['ranker', 11, False]
['ranker', 12, False]
['ranker', 13, False]
['ranker', 14, False]
['ranker', 15, False]
['ranker', 16, False]
['ranker', 17, False]
['ranker', 18, False]
['ranker', 19, False]
['ranker', 20, False]
['ranker', 21, False]
['ranker', 22, False]
['ranker', 23, False]
['ranker', 24, False]
['ranker', 25, False]
['ranker', 26, False]
['ranker', 27, False]
['ranker', 28, False]
['ranker', 29, False]
['ranker', 30, False]
['ranker', 31, False]
['ranker', 32, False]
['ranker', 33, False]
['ranker', 34, False]
['ranker', 35, False]
['ranker', 36, False]
['ranker', 37, False]
['ranker', 38, False]
['ranker', 39, False]
['ranker', 40, False]
['ranker', 41, False]
['ranker', 42, False]
['ranker', 43, False]
['ranker', 44, False]
['ranker', 45, False]
['ranker', 46, False]


In [61]:
agg_ranking_0_satisfied_array

[['ranker', 1, True],
 ['ranker', 2, True],
 ['ranker', 3, True],
 ['ranker', 4, False],
 ['ranker', 5, False],
 ['ranker', 6, False],
 ['ranker', 7, False],
 ['ranker', 8, False],
 ['ranker', 9, False],
 ['ranker', 10, False],
 ['ranker', 11, False],
 ['ranker', 12, False],
 ['ranker', 13, False],
 ['ranker', 14, False],
 ['ranker', 15, False],
 ['ranker', 16, False],
 ['ranker', 17, False],
 ['ranker', 18, False],
 ['ranker', 19, False],
 ['ranker', 20, False],
 ['ranker', 21, False],
 ['ranker', 22, False],
 ['ranker', 23, False],
 ['ranker', 24, False],
 ['ranker', 25, False],
 ['ranker', 26, False],
 ['ranker', 27, False],
 ['ranker', 28, False],
 ['ranker', 29, False],
 ['ranker', 30, False],
 ['ranker', 31, False],
 ['ranker', 32, False],
 ['ranker', 33, False],
 ['ranker', 34, False],
 ['ranker', 35, False],
 ['ranker', 36, False],
 ['ranker', 37, False],
 ['ranker', 38, False],
 ['ranker', 39, False],
 ['ranker', 40, False],
 ['ranker', 41, False],
 ['ranker', 42, False],
 ['r

In [83]:
agg_ranking_0_satisfied_array=[]
k_threshold=threshold
for k in range(1,100):
    agg_ranking_0_k =pd.DataFrame(columns=['id', 'ranker'])
    agg_ranking_0_k["id"]=np.arange(0,100,1)
    agg_ranking_0_k["ranker"]=agg_ranking_1
    agg_ranking_0_k_m =agg_ranking_0_k.head(30).to_numpy()
    agg_ranking_0_k_w =agg_ranking_0_k.tail(70).to_numpy()
    agg_ranking_0_k_groups=np.array([agg_ranking_0_k_m,agg_ranking_0_k_w], dtype=object)
    agg_ranking_0_k_satisfied=metrics.top_k_parity(agg_ranking_0_k_groups,k,k_threshold )
    print(["ranker",k,agg_ranking_0_k_satisfied])
    agg_ranking_0_satisfied_array.append(["ranker",k,agg_ranking_0_k_satisfied])

['ranker', 1, True]
['ranker', 2, True]
['ranker', 3, True]
['ranker', 4, False]
['ranker', 5, False]
['ranker', 6, False]
['ranker', 7, False]
['ranker', 8, False]
['ranker', 9, False]
['ranker', 10, False]
['ranker', 11, False]
['ranker', 12, False]
['ranker', 13, False]
['ranker', 14, False]
['ranker', 15, False]
['ranker', 16, False]
['ranker', 17, False]
['ranker', 18, False]
['ranker', 19, False]
['ranker', 20, False]
['ranker', 21, False]
['ranker', 22, False]
['ranker', 23, False]
['ranker', 24, False]
['ranker', 25, False]
['ranker', 26, False]
['ranker', 27, False]
['ranker', 28, False]
['ranker', 29, False]
['ranker', 30, False]
['ranker', 31, False]
['ranker', 32, False]
['ranker', 33, False]
['ranker', 34, False]
['ranker', 35, False]
['ranker', 36, False]
['ranker', 37, False]
['ranker', 38, False]
['ranker', 39, False]
['ranker', 40, False]
['ranker', 41, False]
['ranker', 42, False]
['ranker', 43, False]
['ranker', 44, False]
['ranker', 45, False]
['ranker', 46, False]


In [63]:
ranking_mc_0_m=np.c_[np.arange(30),agg_ranking_0[:30]]
ranking_mc_0_w=np.c_[np.arange(30,100),agg_ranking_0[30:]]
#ranking_mc_1_m=np.c_[np.arange(30),agg_ranking_1[:30]]
#ranking_mc_1_w=np.c_[np.arange(30,100),agg_ranking_1[30:]]
ranking_mc_0_m,ranking_mc_0_w,#ranking_mc_1_m,#ranking_mc_1_w

(array([[ 0, 31],
        [ 1, 16],
        [ 2, 17],
        [ 3, 38],
        [ 4, 34],
        [ 5, 52],
        [ 6, 58],
        [ 7, 42],
        [ 8, 48],
        [ 9, 45],
        [10, 18],
        [11, 28],
        [12, 39],
        [13, 77],
        [14, 51],
        [15, 90],
        [16, 80],
        [17, 89],
        [18, 98],
        [19, 93],
        [20, 29],
        [21, 72],
        [22, 94],
        [23, 74],
        [24, 49],
        [25, 88],
        [26, 63],
        [27, 95],
        [28, 92],
        [29, 64]], dtype=int64),
 array([[30,  3],
        [31,  0],
        [32, 14],
        [33, 37],
        [34,  7],
        [35, 32],
        [36, 22],
        [37, 27],
        [38, 11],
        [39, 26],
        [40,  5],
        [41, 50],
        [42,  8],
        [43,  4],
        [44,  9],
        [45,  2],
        [46,  6],
        [47,  1],
        [48, 12],
        [49, 25],
        [50, 23],
        [51, 30],
        [52, 13],
        [53, 21],
        [54, 

In [64]:


parity_mc_0=metrics.pairwise_statistical_parity(ranking_mc_0_m,ranking_mc_0_w)
parity_mc_0,

(-0.26571428571428574,)

In [65]:
n_voter,n_candidate=rankings.shape

In [66]:
kemeny_ranking=ul.aggregate_kemeny(n_voter,n_candidate,rankings)

1
2
3
4
5


In [67]:

kemeny_ranking_gurobi=kemeny_ranking
kemeny_ranking_gurobi

(array([68.,  0.,  2., 73., 75., 76., 77., 78., 79., 80.,  4.,  5., 81.,
        82., 83., 85., 86., 87., 88., 89.,  6., 90., 91., 92., 93., 94.,
        95., 96., 97., 98.,  1.,  3.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 22., 16., 17., 18., 19., 20., 21., 23., 24., 25., 26.,
        27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
        40., 41., 42., 43., 44., 45., 99., 46., 47., 48., 49., 50., 51.,
        52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
        65., 66., 67., 69., 70., 71., 84., 72., 74.]),
 10.22163724899292)

In [68]:
kemeny_dist_gurobi=ul.kemeny_dist(rankings,kemeny_ranking[0])
kemeny_dist_gurobi

20680

In [69]:
kemeny_ranking_gurobi_m=np.c_[np.arange(30),kemeny_ranking_gurobi[0][:30]]
kemeny_ranking_gurobi_w=np.c_[np.arange(30,100),kemeny_ranking_gurobi[0][30:]]
parity_kemeny_ranking_gurobi=metrics.pairwise_statistical_parity(kemeny_ranking_gurobi_m,kemeny_ranking_gurobi_w)
parity_kemeny_ranking_gurobi

-0.6333333333333333

In [70]:
fair_kemeny_ranking_gurobi_attribute=attribute[:,1]
fair_kemeny_ranking_gurobi_attribute[1]-fair_kemeny_ranking_gurobi_attribute[50],type(fair_kemeny_ranking_gurobi_attribute[0])

(-1, numpy.int32)

In [71]:
fair_kemeny_ranking_gurobi=ul.aggregate_parity(n_voter,n_candidate,rankings,fair_kemeny_ranking_gurobi_attribute,threshold)

In [72]:
fair_kemeny_ranking_gurobi

(array([ 3.,  4.,  5.,  6.,  7.,  8., 82.,  9., 10., 11., 12., 13., 14.,
        83., 16., 84., 85., 86., 87., 88., 15., 89., 90., 91., 17., 92.,
        93., 94., 95., 96., 18.,  0., 19., 21., 20., 22., 23., 24., 25.,
        26., 27., 28., 29., 30., 31.,  1., 32.,  2., 33., 34., 35., 36.,
        37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.,
        50., 51., 52., 53., 54., 55., 97., 56., 57., 58., 60., 59., 61.,
        62., 63., 64., 65., 66., 67., 68., 69., 70., 98., 71., 72., 73.,
        74., 75., 76., 77., 78., 79., 99., 80., 81.]),
 130.854590177536)

In [73]:
optimal_fair_kemeny_ranking_gurobi_permutation=np.argsort(fair_kemeny_ranking_gurobi[0])
fair_kemeny_ranking_gurobi,optimal_fair_kemeny_ranking_gurobi_permutation

((array([ 3.,  4.,  5.,  6.,  7.,  8., 82.,  9., 10., 11., 12., 13., 14.,
         83., 16., 84., 85., 86., 87., 88., 15., 89., 90., 91., 17., 92.,
         93., 94., 95., 96., 18.,  0., 19., 21., 20., 22., 23., 24., 25.,
         26., 27., 28., 29., 30., 31.,  1., 32.,  2., 33., 34., 35., 36.,
         37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.,
         50., 51., 52., 53., 54., 55., 97., 56., 57., 58., 60., 59., 61.,
         62., 63., 64., 65., 66., 67., 68., 69., 70., 98., 71., 72., 73.,
         74., 75., 76., 77., 78., 79., 99., 80., 81.]),
  130.854590177536),
 array([31, 45, 47,  0,  1,  2,  3,  4,  5,  7,  8,  9, 10, 11, 12, 20, 14,
        24, 30, 32, 34, 33, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 46, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 72, 73, 74, 76, 75, 77, 78, 79, 80, 81, 82, 83,
        84, 85, 86, 88, 89, 90, 91, 92, 93, 94, 95, 96, 98, 99,  6, 13, 15,
        16, 17, 18, 19, 2

In [74]:
fair_kemeny_dist_gurobi=ul.kemeny_dist(rankings,fair_kemeny_ranking_gurobi[0])

In [75]:
fair_kemeny_dist_gurobi

21060

In [76]:
fair_kemeny_ranking_gurobi_m=np.c_[np.arange(30),fair_kemeny_ranking_gurobi[0][:30]]
fair_kemeny_ranking_gurobi_w=np.c_[np.arange(30,100),fair_kemeny_ranking_gurobi[0][30:]]

In [77]:
fair_kemeny_ranking_gurobi_w,fair_kemeny_ranking_gurobi_m

(array([[30., 18.],
        [31.,  0.],
        [32., 19.],
        [33., 21.],
        [34., 20.],
        [35., 22.],
        [36., 23.],
        [37., 24.],
        [38., 25.],
        [39., 26.],
        [40., 27.],
        [41., 28.],
        [42., 29.],
        [43., 30.],
        [44., 31.],
        [45.,  1.],
        [46., 32.],
        [47.,  2.],
        [48., 33.],
        [49., 34.],
        [50., 35.],
        [51., 36.],
        [52., 37.],
        [53., 38.],
        [54., 39.],
        [55., 40.],
        [56., 41.],
        [57., 42.],
        [58., 43.],
        [59., 44.],
        [60., 45.],
        [61., 46.],
        [62., 47.],
        [63., 48.],
        [64., 49.],
        [65., 50.],
        [66., 51.],
        [67., 52.],
        [68., 53.],
        [69., 54.],
        [70., 55.],
        [71., 97.],
        [72., 56.],
        [73., 57.],
        [74., 58.],
        [75., 60.],
        [76., 59.],
        [77., 61.],
        [78., 62.],
        [79., 63.],


In [78]:
parity_fair_kemeny_ranking_gurobi=metrics.pairwise_statistical_parity(fair_kemeny_ranking_gurobi_m,fair_kemeny_ranking_gurobi_w)

In [79]:
parity_fair_kemeny_ranking_gurobi

0.0

In [80]:
fair_kemeny_ranking_gurobi_satisfied_array=[]
k_threshold=0.05
for k in range(1,100):
    fair_kemeny_ranking_gurobi_k =pd.DataFrame(columns=['id', 'ranker'])
    fair_kemeny_ranking_gurobi_k["id"]=np.arange(0,100,1)
    fair_kemeny_ranking_gurobi_k["ranker"]=fair_kemeny_ranking_gurobi[0]
    fair_kemeny_ranking_gurobi_k_m =fair_kemeny_ranking_gurobi_k.head(30).to_numpy()
    fair_kemeny_ranking_gurobi_k_w =fair_kemeny_ranking_gurobi_k.tail(70).to_numpy()
    fair_kemeny_ranking_gurobi_k_groups=np.array([fair_kemeny_ranking_gurobi_k_m,fair_kemeny_ranking_gurobi_k_w], dtype=object)
    fair_kemeny_ranking_gurobi_k_satisfied=metrics.top_k_parity(fair_kemeny_ranking_gurobi_k_groups,k,k_threshold )
    fair_kemeny_ranking_gurobi_satisfied_array.append(["ranker",k,fair_kemeny_ranking_gurobi_k_satisfied])

In [81]:
fair_kemeny_ranking_gurobi_satisfied_array

[['ranker', 1, True],
 ['ranker', 2, True],
 ['ranker', 3, True],
 ['ranker', 4, True],
 ['ranker', 5, True],
 ['ranker', 6, True],
 ['ranker', 7, False],
 ['ranker', 8, False],
 ['ranker', 9, False],
 ['ranker', 10, False],
 ['ranker', 11, False],
 ['ranker', 12, False],
 ['ranker', 13, False],
 ['ranker', 14, False],
 ['ranker', 15, False],
 ['ranker', 16, False],
 ['ranker', 17, False],
 ['ranker', 18, False],
 ['ranker', 19, False],
 ['ranker', 20, False],
 ['ranker', 21, False],
 ['ranker', 22, False],
 ['ranker', 23, False],
 ['ranker', 24, False],
 ['ranker', 25, False],
 ['ranker', 26, False],
 ['ranker', 27, False],
 ['ranker', 28, False],
 ['ranker', 29, False],
 ['ranker', 30, False],
 ['ranker', 31, False],
 ['ranker', 32, False],
 ['ranker', 33, False],
 ['ranker', 34, False],
 ['ranker', 35, False],
 ['ranker', 36, False],
 ['ranker', 37, False],
 ['ranker', 38, False],
 ['ranker', 39, False],
 ['ranker', 40, False],
 ['ranker', 41, True],
 ['ranker', 42, True],
 ['ranker

In [82]:
stationary_distribute_0 = mc.stationary_distribute(rankings, 0)
stationary_distribute_1 = mc.stationary_distribute(rankings, 1)
stationary_distribute_0, stationary_distribute_1

TypeError: stationary_distribute() missing 2 required positional arguments: 'out_degree_matrix' and 'type'

In [ ]:
transition_matrix_0 = mc.generate_transition_matrix(rankings)
transition_matrix_1 = mc.generate_transition_matrix_without_self_circle(rankings)
#sum_of_probability_candidate=np.array([np.sum(transition_matrix_2[i, :]) for i in range(rankings.shape[1])])

transition_matrix_0[30],transition_matrix_1[30]