In [1]:
import numpy as np
import markov_chains_methods as mc
import utils as ul
import pandas as pd
import metrics
from time import time

In [2]:

df=pd.read_csv('20230918dataset_uf.csv')
#add a ranking all m candidates has smaller rank than w's
df["ranker 11"]=np.arange(1,101,1)
#add a ranking half  m candidates on the top of ranking and another half m candidates on the bottom of rinking and w candidates on the middle  
ranker_12=np.concatenate((np.arange(1,16,1),np.arange(86,101,1),np.arange(16,86,1)), axis=None)
#print(ranker_12)
df["ranker 12"]=ranker_12
df=df.drop(['ranker 9','ranker 10'],axis=1)
df


Unnamed: 0  ranker 1  ranker 2  ranker 3  ranker 4  ranker 5  ranker 6  \
0         M01        20        86        79        32        28        70   
1         M02        14         9         7        52        55        26   
2         M03        22         3        24        31        97        29   
3         M04        54        87        13        22        95        46   
4         M05        93         6        53        92        31        10   
..        ...       ...       ...       ...       ...       ...       ...   
95        W66        44        29        85        15        72        11   
96        W67        50        66        29        83         4        81   
97        W68        65        75        78        80        68        12   
98        W69        41        60         9        34        99        30   
99        W70        70        43        19        38        29        35   

    ranker 7  ranker 8  ranker 11  ranker 12  
0         21        71          1          1  
1         89        72          2          2  
2         41        73          3          3  
3         32        74          4          4  
4         56        75          5          5  
..       ...       ...        ...        ...  
95        67        66         96         81  
96        40        67         97         82  
97        73        68         98         83  
98        63        69         99         84  
99        52        70        100         85  

[100 rows x 11 columns]

In [3]:
rankings=df[df.columns[1:]].to_numpy()
rankings

array([[ 20,  86,  79,  32,  28,  70,  21,  71,   1,   1],
       [ 14,   9,   7,  52,  55,  26,  89,  72,   2,   2],
       [ 22,   3,  24,  31,  97,  29,  41,  73,   3,   3],
       [ 54,  87,  13,  22,  95,  46,  32,  74,   4,   4],
       [ 93,   6,  53,  92,  31,  10,  56,  75,   5,   5],
       [ 24,  38,  88,   2, 100,  61,  68,  76,   6,   6],
       [ 10,  45,  31,  59,  98,  84,  80,  77,   7,   7],
       [ 85,  37,  77,  76,  19,   3,  50,  78,   8,   8],
       [ 59,  70,  44,  53,  27,  54,  49,  79,   9,   9],
       [ 31,  97,  97,  25,  77,   1,  16,  80,  10,  10],
       [ 58,  90,   5,   6,  18,  67,   8,  81,  11,  11],
       [ 12,  49,  90,  44,  67,   6,   2,  82,  12,  12],
       [ 47,  63,  60,  69,  32,  15,  19,  83,  13,  13],
       [ 86,  61,  43,  49,  37,  63,  97,  84,  14,  14],
       [ 21,  69,  49,  63,   8,  65,  57,  85,  15,  15],
       [ 17,  46,  34,  97,  91,  36,  91,  86,  16,  86],
       [ 71,  76,  70,  64,  39,  24,  14,  87,  17,  87

In [4]:

rankings=rankings.transpose()
rankings,rankings.shape


(array([[ 20,  14,  22,  54,  93,  24,  10,  85,  59,  31,  58,  12,  47,
          86,  21,  17,  71,   2,  94,  76,  36,   6,  56,  43,  19,  48,
          64,  33,  52,  23,  16,  11,  99,  38,  92,  84,  90,  75,  30,
          97,  13,  78,   5,  42,  62,   4,  88,  40,  15,  68,  29,  87,
          91,  46,  72,  74,  57,  25,  49,   7,  18,  66,  35,  60,  28,
          45,  83,  77,  80,   1,   9,  89,  81,  39,  73,  37,  27,  53,
          98,  34,  55,  69,  67,  82,  96,  79,  63, 100,  95,   3,  32,
          26,   8,  61,  51,  44,  50,  65,  41,  70],
        [ 86,   9,   3,  87,   6,  38,  45,  37,  70,  97,  90,  49,  63,
          61,  69,  46,  76,  74,  15,  80,  16,  17,  95,  89,   4,   5,
          58,  36,  59,  33,  39,  30,  28,  77,  26,  91,  47,  52,  88,
          24,   2, 100,  44,  92,  40,  22,  14,  72,  42,  13,  41,  18,
          10,  82,  57,  48,  27,  85,   7,  98,  68,  65,  54,  94,  64,
          35,  79,  81,  19,  73,  12,  96,  78,  50,  34

In [5]:
threshold=0.01

In [6]:

attribute = np.append(np.repeat(0, 30), np.repeat(1, 70))
attribute=np.c_[np.arange(100),attribute]
df_groups=pd.DataFrame(attribute,columns=['id','attribute'])
groups=df_groups.groupby(df_groups.columns[1]).count()
groups=groups.to_numpy()
groups=np.c_[np.array([[0],[1]]),groups]

group_proportions =mc.proportions(groups)
transition_matrix = mc.generate_transition_matrix(rankings)
size_candidate = rankings.shape[1]

In [7]:
attribute

array([[ 0,  0],
       [ 1,  0],
       [ 2,  0],
       [ 3,  0],
       [ 4,  0],
       [ 5,  0],
       [ 6,  0],
       [ 7,  0],
       [ 8,  0],
       [ 9,  0],
       [10,  0],
       [11,  0],
       [12,  0],
       [13,  0],
       [14,  0],
       [15,  0],
       [16,  0],
       [17,  0],
       [18,  0],
       [19,  0],
       [20,  0],
       [21,  0],
       [22,  0],
       [23,  0],
       [24,  0],
       [25,  0],
       [26,  0],
       [27,  0],
       [28,  0],
       [29,  0],
       [30,  1],
       [31,  1],
       [32,  1],
       [33,  1],
       [34,  1],
       [35,  1],
       [36,  1],
       [37,  1],
       [38,  1],
       [39,  1],
       [40,  1],
       [41,  1],
       [42,  1],
       [43,  1],
       [44,  1],
       [45,  1],
       [46,  1],
       [47,  1],
       [48,  1],
       [49,  1],
       [50,  1],
       [51,  1],
       [52,  1],
       [53,  1],
       [54,  1],
       [55,  1],
       [56,  1],
       [57,  1],
       [58,  1

In [8]:
fair_kemeny_rankings_greedy_t0=time()
fair_kemeny_rankings_greedy=mc.fair_kemeny_mc_rankings_greedy(rankings,attribute,groups,threshold)
fair_kemeny_rankings_greedy_t1=time()
fair_kemeny_rankings_greedy_t1-fair_kemeny_rankings_greedy_t0

[[0.409 0.006 0.006 ... 0.006 0.006 0.006]
 [0.004 0.328 0.007 ... 0.007 0.007 0.006]
 [0.004 0.003 0.326 ... 0.007 0.008 0.007]
 ...
 [0.004 0.003 0.003 ... 0.7   0.005 0.005]
 [0.004 0.003 0.002 ... 0.005 0.588 0.007]
 [0.004 0.004 0.003 ... 0.005 0.003 0.541]]


13.438883781433105

In [9]:
[row[1] for row in fair_kemeny_rankings_greedy]

[29512,
 29144,
 29266,
 29626,
 29434,
 29640,
 29588,
 29464,
 29508,
 29616,
 29400,
 29404,
 29436,
 29534,
 29474,
 29694,
 29568,
 29836,
 29722,
 29522,
 29438,
 29524,
 29732,
 29376,
 29286,
 29710,
 29624,
 29612,
 29734,
 29752,
 29240,
 29130,
 29408,
 29512,
 29346,
 29524,
 29640,
 29524,
 29374,
 29606,
 29328,
 29814,
 29348,
 29346,
 29406,
 29244,
 29294,
 29282,
 29344,
 29494,
 29706,
 29526,
 29314,
 29590,
 29362,
 29320,
 29650,
 29594,
 29404,
 29678,
 29280,
 29586,
 29558,
 29486,
 29502,
 29536,
 29582,
 29578,
 29584,
 29440,
 29480,
 29650,
 29602,
 29546,
 29540,
 29614,
 29396,
 29624,
 29690,
 29584,
 29372,
 29570,
 29482,
 29548,
 29564,
 29628,
 29514,
 29612,
 29758,
 29608,
 29588,
 29680,
 29664,
 29536,
 29566,
 29658,
 29598,
 29698,
 29772,
 29630]

In [10]:


fair_kemeny_ranking_dist_greedy=np.array([row[1] for row in fair_kemeny_rankings_greedy])

optimal_fair_kemeny_ranking_greedy_index=np.argmin(fair_kemeny_ranking_dist_greedy)
optimal_fair_kemeny_ranking_greedy=fair_kemeny_rankings_greedy[optimal_fair_kemeny_ranking_greedy_index]
optimal_fair_kemeny_ranking_greedy_permutation=np.argsort(optimal_fair_kemeny_ranking_greedy[0])
optimal_fair_kemeny_ranking_greedy_permutation,optimal_fair_kemeny_ranking_greedy

(array([31, 33, 41, 15, 26, 35, 78, 87, 18, 27, 65, 79, 85, 88, 96, 19, 71,
        83, 84, 97, 25, 28, 74, 90, 13, 22, 37, 59, 77, 17, 56, 72, 73, 98,
        23, 49, 81, 99, 16, 67, 70, 86, 36, 89, 14, 53, 82, 91, 21, 29, 50,
        75, 80,  4,  5, 10, 66, 68, 95,  6, 57, 61, 64,  9, 12, 39, 69, 92,
        24, 51, 60, 94,  8, 38, 63, 76, 93,  7, 11, 62, 20, 43, 52, 54, 58,
         1, 32, 42, 46,  3, 40, 44, 55,  2, 34, 48,  0, 30, 47, 45],
       dtype=int64),
 (array([96., 85., 93., 89., 53., 54., 59., 77., 72., 63., 55., 78., 64.,
         24., 44.,  3., 38., 29.,  8., 15., 80., 48., 25., 34., 68., 20.,
          4.,  9., 21., 49., 97.,  0., 86.,  1., 94.,  5., 42., 26., 73.,
         65., 90.,  2., 87., 81., 91., 99., 88., 98., 95., 35., 50., 69.,
         82., 45., 83., 92., 30., 60., 84., 27., 70., 61., 79., 74., 62.,
         10., 56., 39., 57., 66., 40., 16., 31., 32., 22., 51., 75., 28.,
          6., 11., 52., 36., 46., 17., 18., 12., 41.,  7., 13., 43., 23.,
         47.

In [11]:
optimal_fair_kemeny_ranking_greedy_m=np.c_[np.arange(30),optimal_fair_kemeny_ranking_greedy[0][:30]]
optimal_fair_kemeny_ranking_greedy_w=np.c_[np.arange(30,100),optimal_fair_kemeny_ranking_greedy[0][30:]]
parity_optimal_fair_kemeny_ranking_greedy=metrics.pairwise_statistical_parity(optimal_fair_kemeny_ranking_greedy_m,optimal_fair_kemeny_ranking_greedy_w)
parity_optimal_fair_kemeny_ranking_greedy

0.0838095238095238

In [12]:
satisfied_array=[]
for k in range(1,100):
    ranking =pd.DataFrame(columns=['id', 'ranker'])
    ranking["id"]=np.arange(0,100,1)
    ranking["ranker"]=optimal_fair_kemeny_ranking_greedy[0]
    ranking_m =ranking.head(30).to_numpy()
    ranking_w =ranking.tail(70).to_numpy()
    rankings_fair=np.array([ranking_m,ranking_w], dtype=object)
    satisfied=metrics.top_k_parity(rankings_fair,k,threshold )
    satisfied_array.append(["ranker",k,satisfied])

0 0 1 1
1 0 1 1
1 0 1 2
1 1 2 2
1 0 1 3
2 2 3 3
2 1 2 4
2 2 3 4
2 1 2 5
3 3 4 5
2 1 2 6
4 4 5 6
3 2 3 7
4 4 5 7
3 2 3 8
5 5 6 8
3 2 3 9
6 6 7 9
4 2 4 10
6 6 8 10
4 3 4 11
7 7 8 11
4 3 4 12
8 8 9 12
4 3 5 13
9 8 10 13
5 4 5 14
9 9 10 14
5 4 5 15
10 10 11 15
5 4 5 16
11 11 12 16
5 4 6 17
12 11 13 17
6 5 6 18
12 12 13 18
6 5 6 19
13 13 14 19
7 5 7 20
13 13 15 20
7 6 7 21
14 14 15 21
7 6 7 22
15 15 16 22
8 6 8 23
15 15 17 23
8 6 8 24
16 16 18 24
8 7 8 25
17 17 18 25
8 7 9 26
18 17 19 26
9 7 9 27
18 18 20 27
9 8 9 28
19 19 20 28
9 8 9 29
20 20 21 29
10 8 10 30
20 20 22 30
10 8 10 31
21 21 23 31
10 9 10 32
22 22 23 32
11 9 11 33
22 22 24 33
11 9 11 34
23 23 25 34
11 10 11 35
24 24 25 35
11 10 12 36
25 24 26 36
12 10 12 37
25 25 27 37
12 11 12 38
26 26 27 38
13 11 13 39
26 26 28 39
13 11 13 40
27 27 29 40
13 11 13 41
28 28 30 41
13 12 14 42
29 28 30 42
14 12 14 43
29 29 31 43
14 12 14 44
30 30 32 44
14 13 14 45
31 31 32 45
15 13 15 46
31 31 33 46
15 13 15 47
32 32 34 47
15 13 15 48
33 33 35 4

In [13]:
satisfied_array

[['ranker', 1, True],
 ['ranker', 2, True],
 ['ranker', 3, True],
 ['ranker', 4, True],
 ['ranker', 5, True],
 ['ranker', 6, True],
 ['ranker', 7, True],
 ['ranker', 8, True],
 ['ranker', 9, True],
 ['ranker', 10, True],
 ['ranker', 11, True],
 ['ranker', 12, True],
 ['ranker', 13, True],
 ['ranker', 14, True],
 ['ranker', 15, True],
 ['ranker', 16, True],
 ['ranker', 17, True],
 ['ranker', 18, True],
 ['ranker', 19, True],
 ['ranker', 20, True],
 ['ranker', 21, True],
 ['ranker', 22, True],
 ['ranker', 23, True],
 ['ranker', 24, True],
 ['ranker', 25, True],
 ['ranker', 26, True],
 ['ranker', 27, True],
 ['ranker', 28, True],
 ['ranker', 29, True],
 ['ranker', 30, True],
 ['ranker', 31, True],
 ['ranker', 32, True],
 ['ranker', 33, True],
 ['ranker', 34, True],
 ['ranker', 35, True],
 ['ranker', 36, True],
 ['ranker', 37, True],
 ['ranker', 38, True],
 ['ranker', 39, True],
 ['ranker', 40, True],
 ['ranker', 41, True],
 ['ranker', 42, True],
 ['ranker', 43, True],
 ['ranker', 44, True

In [14]:
agg_ranking_0=mc.aggregate_rank_mc(rankings,0)
agg_ranking_1=mc.aggregate_rank_mc(rankings,1)
agg_ranking_0,agg_ranking_1

(array([20,  4,  3, 26, 23, 39, 49, 28, 32, 30,  7, 12, 18, 67, 27, 87, 65,
        85, 96, 90, 10, 62, 94, 59, 25, 79, 43, 95, 81, 45,  5,  2, 38, 73,
        19, 66, 50, 52, 22, 51, 13, 75, 14,  6, 15,  1,  8,  0, 16, 35, 34,
        40, 17, 33, 31,  9, 56, 42, 24, 93, 11, 57, 41, 21, 47, 63, 44, 88,
        83, 29, 46, 99, 77, 37, 72, 70, 36, 69, 80, 86, 61, 55, 74, 91, 78,
        89, 60, 98, 82, 54, 92, 68, 58, 48, 53, 71, 84, 97, 76, 64],
       dtype=int64),
 array([21,  4,  3, 29, 24, 42, 49, 31, 32, 35,  8, 12, 18, 66, 27, 88, 64,
        86, 96, 90, 11, 63, 94, 61, 25, 85, 46, 95, 84, 47,  6,  2, 40, 74,
        20, 67, 51, 55, 23, 52, 13, 78, 17,  5, 15,  1,  7,  0, 14, 33, 34,
        38, 16, 30, 28,  9, 54, 41, 22, 91, 10, 50, 39, 19, 44, 62, 43, 87,
        77, 26, 45, 98, 75, 36, 71, 69, 37, 70, 79, 81, 59, 53, 72, 92, 76,
        89, 56, 99, 82, 58, 93, 68, 60, 48, 57, 73, 83, 97, 80, 65],
       dtype=int64))

In [16]:
agg_ranking_1_rever=99-agg_ranking_1
agg_ranking_1_rever

array([78, 95, 96, 70, 75, 57, 50, 68, 67, 64, 91, 87, 81, 33, 72, 11, 35,
       13,  3,  9, 88, 36,  5, 38, 74, 14, 53,  4, 15, 52, 93, 97, 59, 25,
       79, 32, 48, 44, 76, 47, 86, 21, 82, 94, 84, 98, 92, 99, 85, 66, 65,
       61, 83, 69, 71, 90, 45, 58, 77,  8, 89, 49, 60, 80, 55, 37, 56, 12,
       22, 73, 54,  1, 24, 63, 28, 30, 62, 29, 20, 18, 40, 46, 27,  7, 23,
       10, 43,  0, 17, 41,  6, 31, 39, 51, 42, 26, 16,  2, 19, 34],
      dtype=int64)

In [28]:


t0 = time()


kemeny_dist_0=ul.kemeny_dist(rankings,agg_ranking_0)
t1 = time()
kemeny_dist_1=ul.kemeny_dist(rankings,agg_ranking_1)

kemeny_dist_0,kemeny_dist_1,(t1-t0)

(19126, 19140, 0.16199612617492676)

In [20]:
ranking_mc_0_m=np.c_[np.arange(30),agg_ranking_0[:30]]
ranking_mc_0_w=np.c_[np.arange(30,100),agg_ranking_0[30:]]
ranking_mc_1_m=np.c_[np.arange(30),agg_ranking_1[:30]]
ranking_mc_1_w=np.c_[np.arange(30,100),agg_ranking_1[30:]]
ranking_mc_0_m,ranking_mc_0_w,ranking_mc_1_m,ranking_mc_1_w

(array([[ 0, 20],
        [ 1,  4],
        [ 2,  3],
        [ 3, 26],
        [ 4, 23],
        [ 5, 39],
        [ 6, 49],
        [ 7, 28],
        [ 8, 32],
        [ 9, 30],
        [10,  7],
        [11, 12],
        [12, 18],
        [13, 67],
        [14, 27],
        [15, 87],
        [16, 65],
        [17, 85],
        [18, 96],
        [19, 90],
        [20, 10],
        [21, 62],
        [22, 94],
        [23, 59],
        [24, 25],
        [25, 79],
        [26, 43],
        [27, 95],
        [28, 81],
        [29, 45]], dtype=int64),
 array([[30,  5],
        [31,  2],
        [32, 38],
        [33, 73],
        [34, 19],
        [35, 66],
        [36, 50],
        [37, 52],
        [38, 22],
        [39, 51],
        [40, 13],
        [41, 75],
        [42, 14],
        [43,  6],
        [44, 15],
        [45,  1],
        [46,  8],
        [47,  0],
        [48, 16],
        [49, 35],
        [50, 34],
        [51, 40],
        [52, 17],
        [53, 33],
        [54, 

In [21]:


parity_mc_0=metrics.pairwise_statistical_parity(ranking_mc_0_m,ranking_mc_0_w)
parity_mc_1=metrics.pairwise_statistical_parity(ranking_mc_1_m,ranking_mc_1_w)
parity_mc_0,parity_mc_1

(0.08, 0.04666666666666667)

In [22]:
n_voter,n_candidate=rankings.shape
kemeny_ranking=ul.aggregate_kemeny(n_voter,n_candidate,rankings)

Set parameter Username
Academic license - for non-commercial use only - expires 2024-11-13
1
2
3
4
5


In [23]:

kemeny_ranking,len(kemeny_ranking)

((array([ 6.,  0.,  1.,  7.,  8.,  9., 75., 10., 11., 12., 13., 14., 15.,
         76., 19., 77., 78., 79., 95., 80.,  2., 81., 98., 82., 18., 83.,
         20., 99., 84., 26., 16.,  3., 21., 85., 22., 86., 30., 31., 23.,
         36., 17., 87., 24., 25., 27.,  4., 28.,  5., 29., 32., 33., 34.,
         35., 37., 39., 38., 40., 42., 43., 89., 41., 45., 46., 44., 47.,
         48., 49., 88., 90., 50., 51., 91., 52., 53., 56., 55., 54., 57.,
         58., 59., 60., 61., 62., 92., 63., 93., 64., 94., 65., 66., 96.,
         67., 68., 69., 70., 71., 72., 97., 73., 74.]),
  12.34399962425232),
 2)

In [24]:
kemeny_dist_gurobi=ul.kemeny_dist(rankings,kemeny_ranking[0])
kemeny_dist_gurobi

18480

In [ ]:
stationary_distribute_0 = mc.stationary_distribute(rankings, 0)
stationary_distribute_1 = mc.stationary_distribute(rankings, 1)
stationary_distribute_0, stationary_distribute_1

In [ ]:
transition_matrix_0 = mc.generate_transition_matrix(rankings)
transition_matrix_1 = mc.generate_transition_matrix_without_self_circle(rankings)
#sum_of_probability_candidate=np.array([np.sum(transition_matrix_2[i, :]) for i in range(rankings.shape[1])])

transition_matrix_0[30],transition_matrix_1[30]