In [1]:
import numpy as np
import markov_chains_methods as mc
import utils as ul
import pandas as pd
import metrics
from time import time

In [2]:

df=pd.read_csv('20230918dataset_uf.csv')
#add a ranking all m candidates has smaller rank than w's
df["ranker 11"]=np.arange(1,101,1)
#add a ranking half  m candidates on the top of ranking and another half m candidates on the bottom of rinking and w candidates on the middle  
ranker_12=np.concatenate((np.arange(1,16,1),np.arange(86,101,1),np.arange(16,86,1)), axis=None)
#print(ranker_12)
df["ranker 12"]=ranker_12
df=df.drop(['ranker 9','ranker 10'],axis=1)
df


Unnamed: 0  ranker 1  ranker 2  ranker 3  ranker 4  ranker 5  ranker 6  \
0         M01        20        86        79        32        28        70   
1         M02        14         9         7        52        55        26   
2         M03        22         3        24        31        97        29   
3         M04        54        87        13        22        95        46   
4         M05        93         6        53        92        31        10   
..        ...       ...       ...       ...       ...       ...       ...   
95        W66        44        29        85        15        72        11   
96        W67        50        66        29        83         4        81   
97        W68        65        75        78        80        68        12   
98        W69        41        60         9        34        99        30   
99        W70        70        43        19        38        29        35   

    ranker 7  ranker 8  ranker 11  ranker 12  
0         21        71          1          1  
1         89        72          2          2  
2         41        73          3          3  
3         32        74          4          4  
4         56        75          5          5  
..       ...       ...        ...        ...  
95        67        66         96         81  
96        40        67         97         82  
97        73        68         98         83  
98        63        69         99         84  
99        52        70        100         85  

[100 rows x 11 columns]

In [3]:
rankings=df[df.columns[1:]].to_numpy()
rankings

array([[ 20,  86,  79,  32,  28,  70,  21,  71,   1,   1],
       [ 14,   9,   7,  52,  55,  26,  89,  72,   2,   2],
       [ 22,   3,  24,  31,  97,  29,  41,  73,   3,   3],
       [ 54,  87,  13,  22,  95,  46,  32,  74,   4,   4],
       [ 93,   6,  53,  92,  31,  10,  56,  75,   5,   5],
       [ 24,  38,  88,   2, 100,  61,  68,  76,   6,   6],
       [ 10,  45,  31,  59,  98,  84,  80,  77,   7,   7],
       [ 85,  37,  77,  76,  19,   3,  50,  78,   8,   8],
       [ 59,  70,  44,  53,  27,  54,  49,  79,   9,   9],
       [ 31,  97,  97,  25,  77,   1,  16,  80,  10,  10],
       [ 58,  90,   5,   6,  18,  67,   8,  81,  11,  11],
       [ 12,  49,  90,  44,  67,   6,   2,  82,  12,  12],
       [ 47,  63,  60,  69,  32,  15,  19,  83,  13,  13],
       [ 86,  61,  43,  49,  37,  63,  97,  84,  14,  14],
       [ 21,  69,  49,  63,   8,  65,  57,  85,  15,  15],
       [ 17,  46,  34,  97,  91,  36,  91,  86,  16,  86],
       [ 71,  76,  70,  64,  39,  24,  14,  87,  17,  87

In [4]:

rankings=rankings.transpose()
rankings,rankings.shape


(array([[ 20,  14,  22,  54,  93,  24,  10,  85,  59,  31,  58,  12,  47,
          86,  21,  17,  71,   2,  94,  76,  36,   6,  56,  43,  19,  48,
          64,  33,  52,  23,  16,  11,  99,  38,  92,  84,  90,  75,  30,
          97,  13,  78,   5,  42,  62,   4,  88,  40,  15,  68,  29,  87,
          91,  46,  72,  74,  57,  25,  49,   7,  18,  66,  35,  60,  28,
          45,  83,  77,  80,   1,   9,  89,  81,  39,  73,  37,  27,  53,
          98,  34,  55,  69,  67,  82,  96,  79,  63, 100,  95,   3,  32,
          26,   8,  61,  51,  44,  50,  65,  41,  70],
        [ 86,   9,   3,  87,   6,  38,  45,  37,  70,  97,  90,  49,  63,
          61,  69,  46,  76,  74,  15,  80,  16,  17,  95,  89,   4,   5,
          58,  36,  59,  33,  39,  30,  28,  77,  26,  91,  47,  52,  88,
          24,   2, 100,  44,  92,  40,  22,  14,  72,  42,  13,  41,  18,
          10,  82,  57,  48,  27,  85,   7,  98,  68,  65,  54,  94,  64,
          35,  79,  81,  19,  73,  12,  96,  78,  50,  34

In [5]:
threshold=0

In [6]:
attribute = np.append(np.repeat(0, 30), np.repeat(1, 70))
attribute=np.c_[np.arange(100),attribute]
df_groups=pd.DataFrame(attribute,columns=['id','attribute'])
groups=df_groups.groupby(df_groups.columns[1]).count()
groups=groups.to_numpy()
groups=np.c_[np.array([[0],[1]]),groups]

group_proportions =mc.proportions(groups)
transition_matrix = mc.generate_transition_matrix(rankings)
size_candidate = rankings.shape[1]

In [7]:
attribute

array([[ 0,  0],
       [ 1,  0],
       [ 2,  0],
       [ 3,  0],
       [ 4,  0],
       [ 5,  0],
       [ 6,  0],
       [ 7,  0],
       [ 8,  0],
       [ 9,  0],
       [10,  0],
       [11,  0],
       [12,  0],
       [13,  0],
       [14,  0],
       [15,  0],
       [16,  0],
       [17,  0],
       [18,  0],
       [19,  0],
       [20,  0],
       [21,  0],
       [22,  0],
       [23,  0],
       [24,  0],
       [25,  0],
       [26,  0],
       [27,  0],
       [28,  0],
       [29,  0],
       [30,  1],
       [31,  1],
       [32,  1],
       [33,  1],
       [34,  1],
       [35,  1],
       [36,  1],
       [37,  1],
       [38,  1],
       [39,  1],
       [40,  1],
       [41,  1],
       [42,  1],
       [43,  1],
       [44,  1],
       [45,  1],
       [46,  1],
       [47,  1],
       [48,  1],
       [49,  1],
       [50,  1],
       [51,  1],
       [52,  1],
       [53,  1],
       [54,  1],
       [55,  1],
       [56,  1],
       [57,  1],
       [58,  1

In [8]:
fair_kemeny_rankings_greedy_t0=time()
fair_kemeny_rankings_greedy=mc.fair_kemeny_mc_rankings_greedy(rankings,attribute,groups,threshold,1)
fair_kemeny_rankings_greedy_t1=time()
fair_kemeny_rankings_greedy_t1-fair_kemeny_rankings_greedy_t0

initial: 61


0.25099945068359375

In [9]:
fair_kemeny_rankings_greedy

[(array([83., 13., 50., 16., 86., 39., 53., 84., 49., 96., 70., 26., 30.,
         56., 33., 43.,  3., 95., 60.,  9., 63., 89., 73.,  6., 18., 20.,
         66., 76., 46., 23., 54., 31., 58., 34., 57., 36., 52., 51., 28.,
         32., 27., 71., 37., 65., 25., 62., 29.,  2., 38., 35., 19., 59.,
         79.,  4., 11., 68., 91., 12., 21., 92., 55.,  0., 14.,  5., 75.,
         78.,  1., 74., 87., 67., 88., 85., 98., 15., 99., 97., 22., 90.,
         61., 93., 77., 69.,  7., 80., 81., 45.,  8., 82., 72., 47., 40.,
         24., 41., 64., 48., 42., 94., 44., 17., 10.]),
  23240)]

In [10]:


fair_kemeny_ranking_dist_greedy=np.array([row[1] for row in fair_kemeny_rankings_greedy])

optimal_fair_kemeny_ranking_greedy_index=np.argmin(fair_kemeny_ranking_dist_greedy)
optimal_fair_kemeny_ranking_greedy=fair_kemeny_rankings_greedy[optimal_fair_kemeny_ranking_greedy_index]
optimal_fair_kemeny_ranking_greedy_permutation=np.argsort(optimal_fair_kemeny_ranking_greedy[0])
optimal_fair_kemeny_ranking_greedy_permutation,optimal_fair_kemeny_ranking_greedy

(array([61, 66, 47, 16, 53, 63, 23, 82, 86, 19, 99, 54, 57,  1, 62, 73,  3,
        98, 24, 50, 25, 58, 76, 29, 91, 44, 11, 40, 38, 46, 12, 31, 39, 14,
        33, 49, 35, 42, 48,  5, 90, 92, 95, 15, 97, 85, 28, 89, 94,  8,  2,
        37, 36,  6, 30, 60, 13, 34, 32, 51, 18, 78, 45, 20, 93, 43, 26, 69,
        55, 81, 10, 41, 88, 22, 67, 64, 27, 80, 65, 52, 83, 84, 87,  0,  7,
        71,  4, 68, 70, 21, 77, 56, 59, 79, 96, 17,  9, 75, 72, 74],
       dtype=int64),
 (array([83., 13., 50., 16., 86., 39., 53., 84., 49., 96., 70., 26., 30.,
         56., 33., 43.,  3., 95., 60.,  9., 63., 89., 73.,  6., 18., 20.,
         66., 76., 46., 23., 54., 31., 58., 34., 57., 36., 52., 51., 28.,
         32., 27., 71., 37., 65., 25., 62., 29.,  2., 38., 35., 19., 59.,
         79.,  4., 11., 68., 91., 12., 21., 92., 55.,  0., 14.,  5., 75.,
         78.,  1., 74., 87., 67., 88., 85., 98., 15., 99., 97., 22., 90.,
         61., 93., 77., 69.,  7., 80., 81., 45.,  8., 82., 72., 47., 40.,
         24.

In [11]:
optimal_fair_kemeny_ranking_greedy_m=np.c_[np.arange(30),optimal_fair_kemeny_ranking_greedy[0][:30]]
optimal_fair_kemeny_ranking_greedy_w=np.c_[np.arange(30,100),optimal_fair_kemeny_ranking_greedy[0][30:]]
parity_optimal_fair_kemeny_ranking_greedy=metrics.pairwise_statistical_parity(optimal_fair_kemeny_ranking_greedy_m,optimal_fair_kemeny_ranking_greedy_w)
parity_optimal_fair_kemeny_ranking_greedy

0.010476190476190476

In [12]:
satisfied_array=[]
for k in range(1,100):
    ranking =pd.DataFrame(columns=['id', 'ranker'])
    ranking["id"]=np.arange(0,100,1)
    ranking["ranker"]=optimal_fair_kemeny_ranking_greedy[0]
    ranking_m =ranking.head(30).to_numpy()
    ranking_w =ranking.tail(70).to_numpy()
    rankings_fair=np.array([ranking_m,ranking_w], dtype=object)
    satisfied=metrics.top_k_parity(rankings_fair,k,threshold )
    satisfied_array.append(["ranker",k,satisfied])

In [13]:
satisfied_array

[['ranker', 1, True],
 ['ranker', 2, True],
 ['ranker', 3, True],
 ['ranker', 4, True],
 ['ranker', 5, True],
 ['ranker', 6, True],
 ['ranker', 7, True],
 ['ranker', 8, True],
 ['ranker', 9, True],
 ['ranker', 10, True],
 ['ranker', 11, True],
 ['ranker', 12, True],
 ['ranker', 13, True],
 ['ranker', 14, True],
 ['ranker', 15, True],
 ['ranker', 16, True],
 ['ranker', 17, True],
 ['ranker', 18, True],
 ['ranker', 19, True],
 ['ranker', 20, True],
 ['ranker', 21, True],
 ['ranker', 22, True],
 ['ranker', 23, True],
 ['ranker', 24, True],
 ['ranker', 25, True],
 ['ranker', 26, True],
 ['ranker', 27, True],
 ['ranker', 28, True],
 ['ranker', 29, True],
 ['ranker', 30, True],
 ['ranker', 31, True],
 ['ranker', 32, True],
 ['ranker', 33, True],
 ['ranker', 34, True],
 ['ranker', 35, True],
 ['ranker', 36, True],
 ['ranker', 37, True],
 ['ranker', 38, True],
 ['ranker', 39, True],
 ['ranker', 40, True],
 ['ranker', 41, True],
 ['ranker', 42, True],
 ['ranker', 43, True],
 ['ranker', 44, True

In [14]:
agg_ranking_0=mc.aggregate_rank_mc(rankings,0)
agg_ranking_1=mc.aggregate_rank_mc(rankings,1)
agg_ranking_0,agg_ranking_1

(array([20,  4,  3, 26, 23, 39, 49, 28, 32, 30,  7, 12, 18, 67, 27, 87, 65,
        85, 96, 90, 10, 62, 94, 59, 25, 79, 43, 95, 81, 45,  5,  2, 38, 73,
        19, 66, 50, 52, 22, 51, 13, 75, 14,  6, 15,  1,  8,  0, 16, 35, 34,
        40, 17, 33, 31,  9, 56, 42, 24, 93, 11, 57, 41, 21, 47, 63, 44, 88,
        83, 29, 46, 99, 77, 37, 72, 70, 36, 69, 80, 86, 61, 55, 74, 91, 78,
        89, 60, 98, 82, 54, 92, 68, 58, 48, 53, 71, 84, 97, 76, 64],
       dtype=int64),
 array([21,  4,  3, 29, 24, 42, 49, 31, 32, 35,  8, 12, 18, 66, 27, 88, 64,
        86, 96, 90, 11, 63, 94, 61, 25, 85, 46, 95, 84, 47,  6,  2, 40, 74,
        20, 67, 51, 55, 23, 52, 13, 78, 17,  5, 15,  1,  7,  0, 14, 33, 34,
        38, 16, 30, 28,  9, 54, 41, 22, 91, 10, 50, 39, 19, 44, 62, 43, 87,
        77, 26, 45, 98, 75, 36, 71, 69, 37, 70, 79, 81, 59, 53, 72, 92, 76,
        89, 56, 99, 82, 58, 93, 68, 60, 48, 57, 73, 83, 97, 80, 65],
       dtype=int64))

In [15]:

kemeny_dist_0=ul.kemeny_dist(rankings,agg_ranking_0)
kemeny_dist_1=ul.kemeny_dist(rankings,agg_ranking_1)

kemeny_dist_0,kemeny_dist_1

(19126, 19140)

In [16]:
ranking_mc_0_m=np.c_[np.arange(30),agg_ranking_0[:30]]
ranking_mc_0_w=np.c_[np.arange(30,100),agg_ranking_0[30:]]
ranking_mc_1_m=np.c_[np.arange(30),agg_ranking_1[:30]]
ranking_mc_1_w=np.c_[np.arange(30,100),agg_ranking_1[30:]]
ranking_mc_0_m,ranking_mc_0_w,ranking_mc_1_m,ranking_mc_1_w

(array([[ 0, 20],
        [ 1,  4],
        [ 2,  3],
        [ 3, 26],
        [ 4, 23],
        [ 5, 39],
        [ 6, 49],
        [ 7, 28],
        [ 8, 32],
        [ 9, 30],
        [10,  7],
        [11, 12],
        [12, 18],
        [13, 67],
        [14, 27],
        [15, 87],
        [16, 65],
        [17, 85],
        [18, 96],
        [19, 90],
        [20, 10],
        [21, 62],
        [22, 94],
        [23, 59],
        [24, 25],
        [25, 79],
        [26, 43],
        [27, 95],
        [28, 81],
        [29, 45]], dtype=int64),
 array([[30,  5],
        [31,  2],
        [32, 38],
        [33, 73],
        [34, 19],
        [35, 66],
        [36, 50],
        [37, 52],
        [38, 22],
        [39, 51],
        [40, 13],
        [41, 75],
        [42, 14],
        [43,  6],
        [44, 15],
        [45,  1],
        [46,  8],
        [47,  0],
        [48, 16],
        [49, 35],
        [50, 34],
        [51, 40],
        [52, 17],
        [53, 33],
        [54, 

In [17]:


parity_mc_0=metrics.pairwise_statistical_parity(ranking_mc_0_m,ranking_mc_0_w)
parity_mc_1=metrics.pairwise_statistical_parity(ranking_mc_1_m,ranking_mc_1_w)
parity_mc_0,parity_mc_1

(0.08, 0.04666666666666667)

In [18]:
n_voter,n_candidate=rankings.shape

In [19]:
kemeny_ranking=ul.aggregate_kemeny(n_voter,n_candidate,rankings)

Set parameter Username
Academic license - for non-commercial use only - expires 2024-11-13
1
2
3
4
5


In [20]:

kemeny_ranking,len(kemeny_ranking)

((array([ 6.,  0.,  1.,  7.,  8.,  9., 75., 10., 11., 12., 13., 14., 15.,
         76., 19., 77., 78., 79., 95., 80.,  2., 81., 98., 82., 18., 83.,
         20., 99., 84., 26., 16.,  3., 21., 85., 22., 86., 30., 31., 23.,
         36., 17., 87., 24., 25., 27.,  4., 28.,  5., 29., 32., 33., 34.,
         35., 37., 39., 38., 40., 42., 43., 89., 41., 45., 46., 44., 47.,
         48., 49., 88., 90., 50., 51., 91., 52., 53., 56., 55., 54., 57.,
         58., 59., 60., 61., 62., 92., 63., 93., 64., 94., 65., 66., 96.,
         67., 68., 69., 70., 71., 72., 97., 73., 74.]),
  13.389675855636597),
 2)

In [21]:
kemeny_dist_gurobi=ul.kemeny_dist(rankings,kemeny_ranking[0])
kemeny_dist_gurobi

18480

In [22]:
fair_kemeny_ranking_gurobi_attribute=attribute[:,1]
fair_kemeny_ranking_gurobi_attribute[1]-fair_kemeny_ranking_gurobi_attribute[50],type(fair_kemeny_ranking_gurobi_attribute[0])

(-1, numpy.int32)

In [23]:
fair_kemeny_ranking_gurobi=ul.aggregate_parity(n_voter,n_candidate,rankings,fair_kemeny_ranking_gurobi_attribute,threshold)

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1


In [24]:
fair_kemeny_ranking_gurobi

(array([18.,  0.,  1., 19., 20., 21., 81., 22., 23., 24.,  5., 25., 26.,
        83., 28., 84., 85., 86., 97., 88.,  2., 89., 98., 90., 27., 91.,
        30., 99., 92., 31.,  6.,  3., 29., 87.,  7., 32., 33., 34., 35.,
        38.,  8., 94.,  9., 10., 11.,  4., 12., 13., 14., 36., 39., 37.,
        15., 40., 41., 16., 42., 43., 44., 93., 17., 46., 47., 45., 48.,
        49., 50., 51., 52., 53., 54., 95., 55., 56., 58., 59., 57., 60.,
        61., 62., 63., 64., 65., 66., 67., 69., 68., 96., 70., 72., 74.,
        71., 73., 75., 76., 77., 78., 82., 79., 80.]),
 141.36243414878845)

In [25]:
fair_kemeny_dist_gurobi=ul.kemeny_dist(rankings,fair_kemeny_ranking_gurobi[0])

In [26]:
fair_kemeny_dist_gurobi

18530

In [27]:
fair_kemeny_ranking_gurobi_m=np.c_[np.arange(30),fair_kemeny_ranking_gurobi[0][:30]]
fair_kemeny_ranking_gurobi_w=np.c_[np.arange(30,100),fair_kemeny_ranking_gurobi[0][30:]]

In [28]:
fair_kemeny_ranking_gurobi_w,fair_kemeny_ranking_gurobi_m

(array([[30.,  6.],
        [31.,  3.],
        [32., 29.],
        [33., 87.],
        [34.,  7.],
        [35., 32.],
        [36., 33.],
        [37., 34.],
        [38., 35.],
        [39., 38.],
        [40.,  8.],
        [41., 94.],
        [42.,  9.],
        [43., 10.],
        [44., 11.],
        [45.,  4.],
        [46., 12.],
        [47., 13.],
        [48., 14.],
        [49., 36.],
        [50., 39.],
        [51., 37.],
        [52., 15.],
        [53., 40.],
        [54., 41.],
        [55., 16.],
        [56., 42.],
        [57., 43.],
        [58., 44.],
        [59., 93.],
        [60., 17.],
        [61., 46.],
        [62., 47.],
        [63., 45.],
        [64., 48.],
        [65., 49.],
        [66., 50.],
        [67., 51.],
        [68., 52.],
        [69., 53.],
        [70., 54.],
        [71., 95.],
        [72., 55.],
        [73., 56.],
        [74., 58.],
        [75., 59.],
        [76., 57.],
        [77., 60.],
        [78., 61.],
        [79., 62.],


In [29]:
parity_fair_kemeny_ranking_gurobi=metrics.pairwise_statistical_parity(fair_kemeny_ranking_gurobi_m,fair_kemeny_ranking_gurobi_w)

In [30]:
parity_fair_kemeny_ranking_gurobi

0.0

In [35]:
fair_kemeny_ranking_gurobi_satisfied_array=[]
k_threshold=0.1
for k in range(1,100):
    fair_kemeny_ranking_gurobi_k =pd.DataFrame(columns=['id', 'ranker'])
    fair_kemeny_ranking_gurobi_k["id"]=np.arange(0,100,1)
    fair_kemeny_ranking_gurobi_k["ranker"]=fair_kemeny_ranking_gurobi[0]
    fair_kemeny_ranking_gurobi_k_m =fair_kemeny_ranking_gurobi_k.head(30).to_numpy()
    fair_kemeny_ranking_gurobi_k_w =fair_kemeny_ranking_gurobi_k.tail(70).to_numpy()
    fair_kemeny_ranking_gurobi_k_groups=np.array([fair_kemeny_ranking_gurobi_k_m,fair_kemeny_ranking_gurobi_k_w], dtype=object)
    fair_kemeny_ranking_gurobi_k_satisfied=metrics.top_k_parity(fair_kemeny_ranking_gurobi_k_groups,k,k_threshold )
    fair_kemeny_ranking_gurobi_satisfied_array.append(["ranker",k,fair_kemeny_ranking_gurobi_k_satisfied])

In [36]:
fair_kemeny_ranking_gurobi_satisfied_array

[['ranker', 1, True],
 ['ranker', 2, False],
 ['ranker', 3, False],
 ['ranker', 4, False],
 ['ranker', 5, False],
 ['ranker', 6, False],
 ['ranker', 7, False],
 ['ranker', 8, True],
 ['ranker', 9, True],
 ['ranker', 10, True],
 ['ranker', 11, True],
 ['ranker', 12, True],
 ['ranker', 13, True],
 ['ranker', 14, True],
 ['ranker', 15, True],
 ['ranker', 16, True],
 ['ranker', 17, True],
 ['ranker', 18, True],
 ['ranker', 19, True],
 ['ranker', 20, True],
 ['ranker', 21, True],
 ['ranker', 22, True],
 ['ranker', 23, True],
 ['ranker', 24, True],
 ['ranker', 25, False],
 ['ranker', 26, False],
 ['ranker', 27, False],
 ['ranker', 28, False],
 ['ranker', 29, False],
 ['ranker', 30, False],
 ['ranker', 31, False],
 ['ranker', 32, False],
 ['ranker', 33, False],
 ['ranker', 34, False],
 ['ranker', 35, False],
 ['ranker', 36, False],
 ['ranker', 37, False],
 ['ranker', 38, False],
 ['ranker', 39, False],
 ['ranker', 40, False],
 ['ranker', 41, True],
 ['ranker', 42, True],
 ['ranker', 43, True]

In [33]:
stationary_distribute_0 = mc.stationary_distribute(rankings, 0)
stationary_distribute_1 = mc.stationary_distribute(rankings, 1)
stationary_distribute_0, stationary_distribute_1

(array([0.00636478-0.j, 0.00445895-0.j, 0.00433305-0.j, 0.00697691-0.j,
        0.00678303-0.j, 0.00819253-0.j, 0.0091479 -0.j, 0.00723867-0.j,
        0.00742216-0.j, 0.00737572-0.j, 0.00498958-0.j, 0.00547314-0.j,
        0.00618114-0.j, 0.01109269-0.j, 0.00715125-0.j, 0.01399296-0.j,
        0.01099729-0.j, 0.01370725-0.j, 0.0187458 -0.j, 0.01531436-0.j,
        0.00533095-0.j, 0.01035163-0.j, 0.01732745-0.j, 0.0101525 -0.j,
        0.00683577-0.j, 0.01337098-0.j, 0.00865876-0.j, 0.01760905-0.j,
        0.0135678 -0.j, 0.00888645-0.j, 0.0049487 -0.j, 0.00411924-0.j,
        0.00809632-0.j, 0.01246436-0.j, 0.00627435-0.j, 0.01102661-0.j,
        0.00971973-0.j, 0.0098939 -0.j, 0.0066931 -0.j, 0.00979832-0.j,
        0.00565976-0.j, 0.01319912-0.j, 0.00582666-0.j, 0.00497843-0.j,
        0.00582702-0.j, 0.00386067-0.j, 0.00503643-0.j, 0.00339434-0.j,
        0.00583961-0.j, 0.00777182-0.j, 0.00772563-0.j, 0.00823878-0.j,
        0.00590396-0.j, 0.00743119-0.j, 0.00737774-0.j, 0.005144

In [34]:
transition_matrix_0 = mc.generate_transition_matrix(rankings)
transition_matrix_1 = mc.generate_transition_matrix_without_self_circle(rankings)
#sum_of_probability_candidate=np.array([np.sum(transition_matrix_2[i, :]) for i in range(rankings.shape[1])])

transition_matrix_0[30],transition_matrix_1[30]

(array([0.004, 0.003, 0.005, 0.006, 0.005, 0.005, 0.005, 0.004, 0.005,
        0.005, 0.003, 0.004, 0.004, 0.005, 0.005, 0.008, 0.005, 0.006,
        0.007, 0.006, 0.004, 0.005, 0.008, 0.006, 0.005, 0.006, 0.005,
        0.007, 0.007, 0.005, 0.357, 0.005, 0.006, 0.009, 0.006, 0.009,
        0.008, 0.009, 0.007, 0.007, 0.006, 0.01 , 0.006, 0.007, 0.007,
        0.004, 0.005, 0.006, 0.007, 0.007, 0.008, 0.006, 0.006, 0.008,
        0.007, 0.006, 0.007, 0.008, 0.007, 0.007, 0.007, 0.008, 0.008,
        0.007, 0.008, 0.007, 0.007, 0.008, 0.008, 0.005, 0.006, 0.008,
        0.007, 0.008, 0.007, 0.007, 0.006, 0.006, 0.008, 0.007, 0.007,
        0.007, 0.008, 0.008, 0.007, 0.007, 0.006, 0.008, 0.008, 0.006,
        0.008, 0.007, 0.006, 0.005, 0.007, 0.007, 0.007, 0.008, 0.007,
        0.007]),
 array([0.00622084, 0.00466563, 0.00777605, 0.00933126, 0.00777605,
        0.00777605, 0.00777605, 0.00622084, 0.00777605, 0.00777605,
        0.00466563, 0.00622084, 0.00622084, 0.00777605, 0.00777605