In [1]:
import numpy as np
import markov_chains_methods as mc
import utils as ul
import pandas as pd
import metrics
from time import time

In [2]:

df=pd.read_csv('20230918dataset_uf.csv')
#add a ranking all m candidates has smaller rank than w's
df["ranker 11"]=np.arange(1,101,1)
#add a ranking half  m candidates on the top of ranking and another half m candidates on the bottom of rinking and w candidates on the middle  
ranker_12=np.concatenate((np.arange(1,16,1),np.arange(86,101,1),np.arange(16,86,1)), axis=None)
#print(ranker_12)
df["ranker 12"]=ranker_12
df


Unnamed: 0  ranker 1  ranker 2  ranker 3  ranker 4  ranker 5  ranker 6  \
0         M01        20        86        79        32        28        70   
1         M02        14         9         7        52        55        26   
2         M03        22         3        24        31        97        29   
3         M04        54        87        13        22        95        46   
4         M05        93         6        53        92        31        10   
..        ...       ...       ...       ...       ...       ...       ...   
95        W66        44        29        85        15        72        11   
96        W67        50        66        29        83         4        81   
97        W68        65        75        78        80        68        12   
98        W69        41        60         9        34        99        30   
99        W70        70        43        19        38        29        35   

    ranker 7  ranker 8  ranker 9  ranker 10  ranker 11  ranker 12  
0         21        71        71         71          1          1  
1         89        72        72         72          2          2  
2         41        73        73         73          3          3  
3         32        74        74         74          4          4  
4         56        75        75         75          5          5  
..       ...       ...       ...        ...        ...        ...  
95        67        66        66         66         96         81  
96        40        67        67         67         97         82  
97        73        68        68         68         98         83  
98        63        69        69         69         99         84  
99        52        70        70         70        100         85  

[100 rows x 13 columns]

In [3]:
rankings=df[df.columns[1:]].to_numpy()
rankings

array([[ 20,  86,  79, ...,  71,   1,   1],
       [ 14,   9,   7, ...,  72,   2,   2],
       [ 22,   3,  24, ...,  73,   3,   3],
       ...,
       [ 65,  75,  78, ...,  68,  98,  83],
       [ 41,  60,   9, ...,  69,  99,  84],
       [ 70,  43,  19, ...,  70, 100,  85]], dtype=int64)

In [4]:

rankings=rankings.transpose()
rankings,rankings.shape


(array([[ 20,  14,  22, ...,  65,  41,  70],
        [ 86,   9,   3, ...,  75,  60,  43],
        [ 79,   7,  24, ...,  78,   9,  19],
        ...,
        [ 71,  72,  73, ...,  68,  69,  70],
        [  1,   2,   3, ...,  98,  99, 100],
        [  1,   2,   3, ...,  83,  84,  85]], dtype=int64),
 (12, 100))

In [5]:
threshold=0.01

In [6]:
attribute = np.append(np.repeat(0, 30), np.repeat(1, 70))
attribute=np.c_[np.arange(100),attribute]
df_groups=pd.DataFrame(attribute,columns=['id','attribute'])
groups=df_groups.groupby(df_groups.columns[1]).count()
groups=groups.to_numpy()
groups=np.c_[np.array([[0],[1]]),groups]

group_proportions =mc.proportions(groups)
transition_matrix = mc.generate_transition_matrix(rankings)
size_candidate = rankings.shape[1]

In [7]:
attribute

array([[ 0,  0],
       [ 1,  0],
       [ 2,  0],
       [ 3,  0],
       [ 4,  0],
       [ 5,  0],
       [ 6,  0],
       [ 7,  0],
       [ 8,  0],
       [ 9,  0],
       [10,  0],
       [11,  0],
       [12,  0],
       [13,  0],
       [14,  0],
       [15,  0],
       [16,  0],
       [17,  0],
       [18,  0],
       [19,  0],
       [20,  0],
       [21,  0],
       [22,  0],
       [23,  0],
       [24,  0],
       [25,  0],
       [26,  0],
       [27,  0],
       [28,  0],
       [29,  0],
       [30,  1],
       [31,  1],
       [32,  1],
       [33,  1],
       [34,  1],
       [35,  1],
       [36,  1],
       [37,  1],
       [38,  1],
       [39,  1],
       [40,  1],
       [41,  1],
       [42,  1],
       [43,  1],
       [44,  1],
       [45,  1],
       [46,  1],
       [47,  1],
       [48,  1],
       [49,  1],
       [50,  1],
       [51,  1],
       [52,  1],
       [53,  1],
       [54,  1],
       [55,  1],
       [56,  1],
       [57,  1],
       [58,  1

In [8]:
fair_kemeny_rankings_greedy_t0=time()
fair_kemeny_rankings_greedy=mc.fair_kemeny_mc_rankings_greedy(rankings,attribute,groups,threshold,1)
fair_kemeny_rankings_greedy_t1=time()
fair_kemeny_rankings_greedy_t1-fair_kemeny_rankings_greedy_t0

initial: 61


0.5569946765899658

In [9]:
fair_kemeny_rankings_greedy

[(array([85., 58., 73.,  3., 86., 74., 62., 68.,  6., 75., 65., 25., 29.,
          9., 10., 72., 12., 32., 87., 45., 35., 90., 93., 16., 19., 77.,
         38., 48., 41., 22., 51., 11., 80., 49., 52., 39., 53., 44., 14.,
         30., 26., 42., 54., 36., 17., 34., 28., 27., 55., 21., 20., 81.,
         47., 31., 18., 96., 43., 92., 78., 91., 82.,  0.,  1., 60., 56.,
         61., 40., 24., 89., 83., 33., 46., 15.,  2., 37., 63., 79., 64.,
         88., 57., 50.,  4., 59., 66., 67., 13.,  5., 99., 94., 76., 97.,
         23., 69.,  7., 95., 70., 98., 84., 71.,  8.]),
  27890)]

In [10]:


fair_kemeny_ranking_dist_greedy=np.array([row[1] for row in fair_kemeny_rankings_greedy])

optimal_fair_kemeny_ranking_greedy_index=np.argmin(fair_kemeny_ranking_dist_greedy)
optimal_fair_kemeny_ranking_greedy=fair_kemeny_rankings_greedy[optimal_fair_kemeny_ranking_greedy_index]
optimal_fair_kemeny_ranking_greedy_permutation=np.argsort(optimal_fair_kemeny_ranking_greedy[0])
optimal_fair_kemeny_ranking_greedy_permutation,optimal_fair_kemeny_ranking_greedy

(array([61, 62, 73,  3, 81, 86,  8, 93, 99, 13, 14, 31, 16, 85, 38, 72, 23,
        44, 54, 24, 50, 49, 29, 91, 67, 11, 40, 47, 46, 12, 39, 53, 17, 70,
        45, 20, 43, 74, 26, 35, 66, 28, 41, 56, 37, 19, 71, 52, 27, 33, 80,
        30, 34, 36, 42, 48, 64, 79,  1, 82, 63, 65,  6, 75, 77, 10, 83, 84,
         7, 92, 95, 98, 15,  2,  5,  9, 89, 25, 58, 76, 32, 51, 60, 69, 97,
         0,  4, 18, 78, 68, 21, 59, 57, 22, 88, 94, 55, 90, 96, 87],
       dtype=int64),
 (array([85., 58., 73.,  3., 86., 74., 62., 68.,  6., 75., 65., 25., 29.,
          9., 10., 72., 12., 32., 87., 45., 35., 90., 93., 16., 19., 77.,
         38., 48., 41., 22., 51., 11., 80., 49., 52., 39., 53., 44., 14.,
         30., 26., 42., 54., 36., 17., 34., 28., 27., 55., 21., 20., 81.,
         47., 31., 18., 96., 43., 92., 78., 91., 82.,  0.,  1., 60., 56.,
         61., 40., 24., 89., 83., 33., 46., 15.,  2., 37., 63., 79., 64.,
         88., 57., 50.,  4., 59., 66., 67., 13.,  5., 99., 94., 76., 97.,
         23.

In [11]:
optimal_fair_kemeny_ranking_greedy_m=np.c_[np.arange(30),optimal_fair_kemeny_ranking_greedy[0][:30]]
optimal_fair_kemeny_ranking_greedy_w=np.c_[np.arange(30,100),optimal_fair_kemeny_ranking_greedy[0][30:]]
parity_optimal_fair_kemeny_ranking_greedy=metrics.pairwise_statistical_parity(optimal_fair_kemeny_ranking_greedy_m,optimal_fair_kemeny_ranking_greedy_w)
parity_optimal_fair_kemeny_ranking_greedy

0.02857142857142857

In [12]:
satisfied_array=[]
for k in range(1,100):
    ranking =pd.DataFrame(columns=['id', 'ranker'])
    ranking["id"]=np.arange(0,100,1)
    ranking["ranker"]=optimal_fair_kemeny_ranking_greedy[0]
    ranking_m =ranking.head(30).to_numpy()
    ranking_w =ranking.tail(70).to_numpy()
    rankings_fair=np.array([ranking_m,ranking_w], dtype=object)
    satisfied=metrics.top_k_parity(rankings_fair,k,threshold )
    satisfied_array.append(["ranker",k,satisfied])

In [13]:
satisfied_array=np.array(satisfied_array)
satisfied_array

array([['ranker', '1', 'True'],
       ['ranker', '2', 'True'],
       ['ranker', '3', 'True'],
       ['ranker', '4', 'True'],
       ['ranker', '5', 'True'],
       ['ranker', '6', 'True'],
       ['ranker', '7', 'True'],
       ['ranker', '8', 'True'],
       ['ranker', '9', 'True'],
       ['ranker', '10', 'True'],
       ['ranker', '11', 'True'],
       ['ranker', '12', 'True'],
       ['ranker', '13', 'True'],
       ['ranker', '14', 'True'],
       ['ranker', '15', 'True'],
       ['ranker', '16', 'True'],
       ['ranker', '17', 'True'],
       ['ranker', '18', 'True'],
       ['ranker', '19', 'True'],
       ['ranker', '20', 'True'],
       ['ranker', '21', 'True'],
       ['ranker', '22', 'True'],
       ['ranker', '23', 'True'],
       ['ranker', '24', 'True'],
       ['ranker', '25', 'True'],
       ['ranker', '26', 'True'],
       ['ranker', '27', 'True'],
       ['ranker', '28', 'True'],
       ['ranker', '29', 'True'],
       ['ranker', '30', 'True'],
       ['ranker', '

In [14]:

t0=time()
agg_ranking_0=mc.aggregate_rank_mc(rankings,0)
t1=time()
agg_ranking_1=mc.aggregate_rank_mc(rankings,1)
agg_ranking_0,t1-t0

(array([35, 16, 15, 44, 43, 56, 64, 47, 50, 48, 26, 29, 42, 80, 51, 89, 83,
        90, 98, 94, 37, 81, 97, 82, 57, 91, 72, 99, 93, 78,  3,  1, 19, 46,
        11, 40, 28, 33, 14, 32,  7, 52,  8,  4,  9,  2,  5,  0, 12, 23, 22,
        25, 13, 20, 21,  6, 41, 27, 18, 77, 10, 45, 30, 17, 38, 49, 36, 73,
        66, 24, 39, 92, 68, 31, 65, 63, 34, 62, 71, 76, 55, 53, 69, 87, 74,
        85, 59, 95, 79, 58, 88, 67, 61, 54, 60, 75, 86, 96, 84, 70],
       dtype=int64),
 0.05699944496154785)

In [15]:
agg_ranking_0_satisfied_array=[]
k_threshold=threshold
for k in range(1,100):
    agg_ranking_0_k =pd.DataFrame(columns=['id', 'ranker'])
    agg_ranking_0_k["id"]=np.arange(0,100,1)
    agg_ranking_0_k["ranker"]=agg_ranking_0
    agg_ranking_0_k_m =agg_ranking_0_k.head(30).to_numpy()
    agg_ranking_0_k_w =agg_ranking_0_k.tail(70).to_numpy()
    agg_ranking_0_k_groups=np.array([agg_ranking_0_k_m,agg_ranking_0_k_w], dtype=object)
    agg_ranking_0_k_satisfied=metrics.top_k_parity(agg_ranking_0_k_groups,k,k_threshold )
    print(["ranker",k,agg_ranking_0_k_satisfied])
    agg_ranking_0_satisfied_array.append(["ranker",k,agg_ranking_0_k_satisfied])


['ranker', 1, True]
['ranker', 2, True]
['ranker', 3, True]
['ranker', 4, False]
['ranker', 5, False]
['ranker', 6, False]
['ranker', 7, False]
['ranker', 8, False]
['ranker', 9, False]
['ranker', 10, False]
['ranker', 11, False]
['ranker', 12, False]
['ranker', 13, False]
['ranker', 14, False]
['ranker', 15, False]
['ranker', 16, False]
['ranker', 17, False]
['ranker', 18, False]
['ranker', 19, False]
['ranker', 20, False]
['ranker', 21, False]
['ranker', 22, False]
['ranker', 23, False]
['ranker', 24, False]
['ranker', 25, False]
['ranker', 26, False]
['ranker', 27, False]
['ranker', 28, False]
['ranker', 29, False]
['ranker', 30, False]
['ranker', 31, False]
['ranker', 32, False]
['ranker', 33, False]
['ranker', 34, False]
['ranker', 35, False]
['ranker', 36, False]
['ranker', 37, False]
['ranker', 38, False]
['ranker', 39, False]
['ranker', 40, False]
['ranker', 41, False]
['ranker', 42, False]
['ranker', 43, False]
['ranker', 44, False]
['ranker', 45, False]
['ranker', 46, False]


In [16]:
agg_ranking_0_satisfied_array

[['ranker', 1, True],
 ['ranker', 2, True],
 ['ranker', 3, True],
 ['ranker', 4, False],
 ['ranker', 5, False],
 ['ranker', 6, False],
 ['ranker', 7, False],
 ['ranker', 8, False],
 ['ranker', 9, False],
 ['ranker', 10, False],
 ['ranker', 11, False],
 ['ranker', 12, False],
 ['ranker', 13, False],
 ['ranker', 14, False],
 ['ranker', 15, False],
 ['ranker', 16, False],
 ['ranker', 17, False],
 ['ranker', 18, False],
 ['ranker', 19, False],
 ['ranker', 20, False],
 ['ranker', 21, False],
 ['ranker', 22, False],
 ['ranker', 23, False],
 ['ranker', 24, False],
 ['ranker', 25, False],
 ['ranker', 26, False],
 ['ranker', 27, False],
 ['ranker', 28, False],
 ['ranker', 29, False],
 ['ranker', 30, False],
 ['ranker', 31, False],
 ['ranker', 32, False],
 ['ranker', 33, False],
 ['ranker', 34, False],
 ['ranker', 35, False],
 ['ranker', 36, False],
 ['ranker', 37, False],
 ['ranker', 38, False],
 ['ranker', 39, False],
 ['ranker', 40, False],
 ['ranker', 41, False],
 ['ranker', 42, False],
 ['r

In [17]:
t0=time()
kemeny_dist_0=ul.kemeny_dist(rankings,agg_ranking_0)
kemeny_dist_1=ul.kemeny_dist(rankings,agg_ranking_1)

kemeny_dist_0,kemeny_dist_1

(22276, 22372)

In [18]:
ranking_mc_0_m=np.c_[np.arange(30),agg_ranking_0[:30]]
ranking_mc_0_w=np.c_[np.arange(30,100),agg_ranking_0[30:]]
ranking_mc_1_m=np.c_[np.arange(30),agg_ranking_1[:30]]
ranking_mc_1_w=np.c_[np.arange(30,100),agg_ranking_1[30:]]
ranking_mc_0_m,ranking_mc_0_w,ranking_mc_1_m,ranking_mc_1_w

(array([[ 0, 35],
        [ 1, 16],
        [ 2, 15],
        [ 3, 44],
        [ 4, 43],
        [ 5, 56],
        [ 6, 64],
        [ 7, 47],
        [ 8, 50],
        [ 9, 48],
        [10, 26],
        [11, 29],
        [12, 42],
        [13, 80],
        [14, 51],
        [15, 89],
        [16, 83],
        [17, 90],
        [18, 98],
        [19, 94],
        [20, 37],
        [21, 81],
        [22, 97],
        [23, 82],
        [24, 57],
        [25, 91],
        [26, 72],
        [27, 99],
        [28, 93],
        [29, 78]], dtype=int64),
 array([[30,  3],
        [31,  1],
        [32, 19],
        [33, 46],
        [34, 11],
        [35, 40],
        [36, 28],
        [37, 33],
        [38, 14],
        [39, 32],
        [40,  7],
        [41, 52],
        [42,  8],
        [43,  4],
        [44,  9],
        [45,  2],
        [46,  5],
        [47,  0],
        [48, 12],
        [49, 23],
        [50, 22],
        [51, 25],
        [52, 13],
        [53, 20],
        [54, 

In [19]:


parity_mc_0=metrics.pairwise_statistical_parity(ranking_mc_0_m,ranking_mc_0_w)
parity_mc_0,

(-0.38285714285714284,)

In [20]:
n_voter,n_candidate=rankings.shape

In [21]:
kemeny_ranking=ul.aggregate_kemeny(n_voter,n_candidate,rankings)

Set parameter Username
Academic license - for non-commercial use only - expires 2024-11-13
1
2
3
4
5


In [25]:

kemeny_ranking_gurobi=kemeny_ranking
kemeny_ranking_gurobi

(array([68.,  0.,  2., 73., 75., 76., 77., 78., 79., 80.,  4.,  5., 81.,
        82., 83., 85., 86., 87., 88., 89.,  6., 90., 91., 92., 93., 94.,
        95., 96., 97., 98.,  1.,  3.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 22., 16., 17., 18., 19., 20., 21., 23., 24., 25., 26.,
        27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
        40., 41., 42., 43., 44., 45., 99., 46., 47., 48., 49., 50., 51.,
        52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
        65., 66., 67., 69., 70., 71., 84., 72., 74.]),
 9.984091520309448)

In [23]:
kemeny_dist_gurobi=ul.kemeny_dist(rankings,kemeny_ranking[0])
kemeny_dist_gurobi

20680

In [24]:
kemeny_ranking_gurobi_m=np.c_[np.arange(30),kemeny_ranking_gurobi[0][:30]]
kemeny_ranking_gurobi_w=np.c_[np.arange(30,100),kemeny_ranking_gurobi[0][30:]]
parity_kemeny_ranking_gurobi=metrics.pairwise_statistical_parity(kemeny_ranking_gurobi_m,kemeny_ranking_gurobi_w)
parity_kemeny_ranking_gurobi

-0.6333333333333333

In [26]:
fair_kemeny_ranking_gurobi_attribute=attribute[:,1]
fair_kemeny_ranking_gurobi_attribute[1]-fair_kemeny_ranking_gurobi_attribute[50],type(fair_kemeny_ranking_gurobi_attribute[0])

(-1, numpy.int32)

In [27]:
fair_kemeny_ranking_gurobi=ul.aggregate_parity(n_voter,n_candidate,rankings,fair_kemeny_ranking_gurobi_attribute,threshold)

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1


In [28]:
fair_kemeny_ranking_gurobi

(array([ 3.,  4.,  5.,  6.,  7.,  8., 82.,  9., 10., 11., 12., 13., 14.,
        83., 16., 84., 85., 86., 87., 88., 15., 89., 90., 91., 17., 92.,
        93., 94., 95., 96., 18.,  0., 19., 21., 20., 22., 23., 24., 25.,
        26., 27., 28., 29., 30., 31.,  1., 32.,  2., 33., 34., 35., 36.,
        37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.,
        50., 51., 52., 53., 54., 55., 97., 56., 57., 58., 60., 59., 61.,
        62., 63., 64., 65., 66., 67., 68., 69., 70., 98., 71., 72., 73.,
        74., 75., 76., 77., 78., 79., 99., 80., 81.]),
 128.50376152992249)

In [29]:
fair_kemeny_dist_gurobi=ul.kemeny_dist(rankings,fair_kemeny_ranking_gurobi[0])

In [30]:
fair_kemeny_dist_gurobi

21060

In [31]:
fair_kemeny_ranking_gurobi_m=np.c_[np.arange(30),fair_kemeny_ranking_gurobi[0][:30]]
fair_kemeny_ranking_gurobi_w=np.c_[np.arange(30,100),fair_kemeny_ranking_gurobi[0][30:]]

In [32]:
fair_kemeny_ranking_gurobi_w,fair_kemeny_ranking_gurobi_m

(array([[30., 18.],
        [31.,  0.],
        [32., 19.],
        [33., 21.],
        [34., 20.],
        [35., 22.],
        [36., 23.],
        [37., 24.],
        [38., 25.],
        [39., 26.],
        [40., 27.],
        [41., 28.],
        [42., 29.],
        [43., 30.],
        [44., 31.],
        [45.,  1.],
        [46., 32.],
        [47.,  2.],
        [48., 33.],
        [49., 34.],
        [50., 35.],
        [51., 36.],
        [52., 37.],
        [53., 38.],
        [54., 39.],
        [55., 40.],
        [56., 41.],
        [57., 42.],
        [58., 43.],
        [59., 44.],
        [60., 45.],
        [61., 46.],
        [62., 47.],
        [63., 48.],
        [64., 49.],
        [65., 50.],
        [66., 51.],
        [67., 52.],
        [68., 53.],
        [69., 54.],
        [70., 55.],
        [71., 97.],
        [72., 56.],
        [73., 57.],
        [74., 58.],
        [75., 60.],
        [76., 59.],
        [77., 61.],
        [78., 62.],
        [79., 63.],


In [33]:
parity_fair_kemeny_ranking_gurobi=metrics.pairwise_statistical_parity(fair_kemeny_ranking_gurobi_m,fair_kemeny_ranking_gurobi_w)

In [34]:
parity_fair_kemeny_ranking_gurobi

0.0

In [35]:
fair_kemeny_ranking_gurobi_satisfied_array=[]
k_threshold=0.1
for k in range(1,100):
    fair_kemeny_ranking_gurobi_k =pd.DataFrame(columns=['id', 'ranker'])
    fair_kemeny_ranking_gurobi_k["id"]=np.arange(0,100,1)
    fair_kemeny_ranking_gurobi_k["ranker"]=fair_kemeny_ranking_gurobi[0]
    fair_kemeny_ranking_gurobi_k_m =fair_kemeny_ranking_gurobi_k.head(30).to_numpy()
    fair_kemeny_ranking_gurobi_k_w =fair_kemeny_ranking_gurobi_k.tail(70).to_numpy()
    fair_kemeny_ranking_gurobi_k_groups=np.array([fair_kemeny_ranking_gurobi_k_m,fair_kemeny_ranking_gurobi_k_w], dtype=object)
    fair_kemeny_ranking_gurobi_k_satisfied=metrics.top_k_parity(fair_kemeny_ranking_gurobi_k_groups,k,k_threshold )
    fair_kemeny_ranking_gurobi_satisfied_array.append(["ranker",k,fair_kemeny_ranking_gurobi_k_satisfied])

In [36]:
fair_kemeny_ranking_gurobi_satisfied_array

[['ranker', 1, True],
 ['ranker', 2, False],
 ['ranker', 3, False],
 ['ranker', 4, False],
 ['ranker', 5, False],
 ['ranker', 6, False],
 ['ranker', 7, False],
 ['ranker', 8, True],
 ['ranker', 9, True],
 ['ranker', 10, True],
 ['ranker', 11, True],
 ['ranker', 12, True],
 ['ranker', 13, True],
 ['ranker', 14, True],
 ['ranker', 15, True],
 ['ranker', 16, True],
 ['ranker', 17, True],
 ['ranker', 18, True],
 ['ranker', 19, True],
 ['ranker', 20, True],
 ['ranker', 21, True],
 ['ranker', 22, True],
 ['ranker', 23, True],
 ['ranker', 24, True],
 ['ranker', 25, False],
 ['ranker', 26, False],
 ['ranker', 27, False],
 ['ranker', 28, False],
 ['ranker', 29, False],
 ['ranker', 30, False],
 ['ranker', 31, False],
 ['ranker', 32, False],
 ['ranker', 33, False],
 ['ranker', 34, False],
 ['ranker', 35, False],
 ['ranker', 36, False],
 ['ranker', 37, False],
 ['ranker', 38, False],
 ['ranker', 39, False],
 ['ranker', 40, False],
 ['ranker', 41, True],
 ['ranker', 42, True],
 ['ranker', 43, True]

In [33]:
stationary_distribute_0 = mc.stationary_distribute(rankings, 0)
stationary_distribute_1 = mc.stationary_distribute(rankings, 1)
stationary_distribute_0, stationary_distribute_1

(array([0.00636478-0.j, 0.00445895-0.j, 0.00433305-0.j, 0.00697691-0.j,
        0.00678303-0.j, 0.00819253-0.j, 0.0091479 -0.j, 0.00723867-0.j,
        0.00742216-0.j, 0.00737572-0.j, 0.00498958-0.j, 0.00547314-0.j,
        0.00618114-0.j, 0.01109269-0.j, 0.00715125-0.j, 0.01399296-0.j,
        0.01099729-0.j, 0.01370725-0.j, 0.0187458 -0.j, 0.01531436-0.j,
        0.00533095-0.j, 0.01035163-0.j, 0.01732745-0.j, 0.0101525 -0.j,
        0.00683577-0.j, 0.01337098-0.j, 0.00865876-0.j, 0.01760905-0.j,
        0.0135678 -0.j, 0.00888645-0.j, 0.0049487 -0.j, 0.00411924-0.j,
        0.00809632-0.j, 0.01246436-0.j, 0.00627435-0.j, 0.01102661-0.j,
        0.00971973-0.j, 0.0098939 -0.j, 0.0066931 -0.j, 0.00979832-0.j,
        0.00565976-0.j, 0.01319912-0.j, 0.00582666-0.j, 0.00497843-0.j,
        0.00582702-0.j, 0.00386067-0.j, 0.00503643-0.j, 0.00339434-0.j,
        0.00583961-0.j, 0.00777182-0.j, 0.00772563-0.j, 0.00823878-0.j,
        0.00590396-0.j, 0.00743119-0.j, 0.00737774-0.j, 0.005144

In [34]:
transition_matrix_0 = mc.generate_transition_matrix(rankings)
transition_matrix_1 = mc.generate_transition_matrix_without_self_circle(rankings)
#sum_of_probability_candidate=np.array([np.sum(transition_matrix_2[i, :]) for i in range(rankings.shape[1])])

transition_matrix_0[30],transition_matrix_1[30]

(array([0.004, 0.003, 0.005, 0.006, 0.005, 0.005, 0.005, 0.004, 0.005,
        0.005, 0.003, 0.004, 0.004, 0.005, 0.005, 0.008, 0.005, 0.006,
        0.007, 0.006, 0.004, 0.005, 0.008, 0.006, 0.005, 0.006, 0.005,
        0.007, 0.007, 0.005, 0.357, 0.005, 0.006, 0.009, 0.006, 0.009,
        0.008, 0.009, 0.007, 0.007, 0.006, 0.01 , 0.006, 0.007, 0.007,
        0.004, 0.005, 0.006, 0.007, 0.007, 0.008, 0.006, 0.006, 0.008,
        0.007, 0.006, 0.007, 0.008, 0.007, 0.007, 0.007, 0.008, 0.008,
        0.007, 0.008, 0.007, 0.007, 0.008, 0.008, 0.005, 0.006, 0.008,
        0.007, 0.008, 0.007, 0.007, 0.006, 0.006, 0.008, 0.007, 0.007,
        0.007, 0.008, 0.008, 0.007, 0.007, 0.006, 0.008, 0.008, 0.006,
        0.008, 0.007, 0.006, 0.005, 0.007, 0.007, 0.007, 0.008, 0.007,
        0.007]),
 array([0.00622084, 0.00466563, 0.00777605, 0.00933126, 0.00777605,
        0.00777605, 0.00777605, 0.00622084, 0.00777605, 0.00777605,
        0.00466563, 0.00622084, 0.00622084, 0.00777605, 0.00777605