In [1]:
import numpy as np
import markov_chains_methods as mc
import utils as ul
import pandas as pd
import metrics
from time import time

In [2]:

df=pd.read_csv('20230918dataset_uf.csv')
#add a ranking all m candidates has smaller rank than w's
df["ranker 11"]=np.arange(1,101,1)
#add a ranking half  m candidates on the top of ranking and another half m candidates on the bottom of rinking and w candidates on the middle  
ranker_12=np.concatenate((np.arange(1,16,1),np.arange(86,101,1),np.arange(16,86,1)), axis=None)
#print(ranker_12)
df["ranker 12"]=ranker_12
df

Unnamed: 0  ranker 1  ranker 2  ranker 3  ranker 4  ranker 5  ranker 6  \
0         M01        20        86        79        32        28        70   
1         M02        14         9         7        52        55        26   
2         M03        22         3        24        31        97        29   
3         M04        54        87        13        22        95        46   
4         M05        93         6        53        92        31        10   
..        ...       ...       ...       ...       ...       ...       ...   
95        W66        44        29        85        15        72        11   
96        W67        50        66        29        83         4        81   
97        W68        65        75        78        80        68        12   
98        W69        41        60         9        34        99        30   
99        W70        70        43        19        38        29        35   

    ranker 7  ranker 8  ranker 9  ranker 10  ranker 11  ranker 12  
0         21        71        71         71          1          1  
1         89        72        72         72          2          2  
2         41        73        73         73          3          3  
3         32        74        74         74          4          4  
4         56        75        75         75          5          5  
..       ...       ...       ...        ...        ...        ...  
95        67        66        66         66         96         81  
96        40        67        67         67         97         82  
97        73        68        68         68         98         83  
98        63        69        69         69         99         84  
99        52        70        70         70        100         85  

[100 rows x 13 columns]

In [3]:
rankings=df[df.columns[1:]].to_numpy()
rankings

array([[ 20,  86,  79, ...,  71,   1,   1],
       [ 14,   9,   7, ...,  72,   2,   2],
       [ 22,   3,  24, ...,  73,   3,   3],
       ...,
       [ 65,  75,  78, ...,  68,  98,  83],
       [ 41,  60,   9, ...,  69,  99,  84],
       [ 70,  43,  19, ...,  70, 100,  85]], dtype=int64)

In [4]:
rankings=rankings.transpose()
rankings,rankings.shape

(array([[ 20,  14,  22, ...,  65,  41,  70],
        [ 86,   9,   3, ...,  75,  60,  43],
        [ 79,   7,  24, ...,  78,   9,  19],
        ...,
        [ 71,  72,  73, ...,  68,  69,  70],
        [  1,   2,   3, ...,  98,  99, 100],
        [  1,   2,   3, ...,  83,  84,  85]], dtype=int64),
 (12, 100))

In [5]:
threshold=0

In [6]:
attribute = np.append(np.repeat(0, 30), np.repeat(1, 70))
attribute=np.c_[np.arange(100),attribute]
df_groups=pd.DataFrame(attribute,columns=['id','attribute'])
groups=df_groups.groupby(df_groups.columns[1]).count()
groups=groups.to_numpy()
groups=np.c_[np.array([[0],[1]]),groups]

group_proportions =mc.proportions(groups)
transition_matrix = mc.generate_transition_matrix(rankings)
size_candidate = rankings.shape[1]

In [7]:
precedence=mc.build_precedence_matrix(rankings)
out_degree=mc.build_out_degree_matrix(precedence)
matrix=mc.incresing_consensus_transition_matrix(rankings,precedence,out_degree)
matrix[0]

array([7.06775000e-01, 4.60000000e-03, 4.92500000e-03, 2.85833333e-03,
       2.86666667e-03, 1.94166667e-03, 1.95000000e-03, 2.15000000e-03,
       2.43333333e-03, 2.11666667e-03, 3.67500000e-03, 3.35833333e-03,
       2.73333333e-03, 1.24166667e-03, 2.15000000e-03, 9.75000000e-04,
       1.40833333e-03, 7.83333333e-04, 5.83333333e-04, 7.75000000e-04,
       2.74166667e-03, 8.33333333e-04, 3.58333333e-04, 7.91666667e-04,
       2.15000000e-03, 3.41666667e-04, 8.08333333e-04, 1.50000000e-04,
       2.50000000e-04, 9.00000000e-04, 6.62500000e-03, 6.98333333e-03,
       5.05000000e-03, 3.10000000e-03, 5.77500000e-03, 3.61666667e-03,
       4.05833333e-03, 3.75000000e-03, 5.27500000e-03, 3.94166667e-03,
       5.99166667e-03, 2.73333333e-03, 5.75000000e-03, 5.89166667e-03,
       5.36666667e-03, 6.41666667e-03, 5.90833333e-03, 6.45833333e-03,
       5.40833333e-03, 4.40833333e-03, 4.53333333e-03, 4.31666667e-03,
       5.15000000e-03, 4.50833333e-03, 4.31666667e-03, 5.31666667e-03,
      

In [8]:
attribute

array([[ 0,  0],
       [ 1,  0],
       [ 2,  0],
       [ 3,  0],
       [ 4,  0],
       [ 5,  0],
       [ 6,  0],
       [ 7,  0],
       [ 8,  0],
       [ 9,  0],
       [10,  0],
       [11,  0],
       [12,  0],
       [13,  0],
       [14,  0],
       [15,  0],
       [16,  0],
       [17,  0],
       [18,  0],
       [19,  0],
       [20,  0],
       [21,  0],
       [22,  0],
       [23,  0],
       [24,  0],
       [25,  0],
       [26,  0],
       [27,  0],
       [28,  0],
       [29,  0],
       [30,  1],
       [31,  1],
       [32,  1],
       [33,  1],
       [34,  1],
       [35,  1],
       [36,  1],
       [37,  1],
       [38,  1],
       [39,  1],
       [40,  1],
       [41,  1],
       [42,  1],
       [43,  1],
       [44,  1],
       [45,  1],
       [46,  1],
       [47,  1],
       [48,  1],
       [49,  1],
       [50,  1],
       [51,  1],
       [52,  1],
       [53,  1],
       [54,  1],
       [55,  1],
       [56,  1],
       [57,  1],
       [58,  1

In [16]:
#fair_kemeny_rankings_greedy_1_t0=time()
#fair_kemeny_rankings_greedy_1=mc.fair_kemeny_mc_rankings_greedy(rankings,attribute,groups,threshold,1)
#fair_kemeny_rankings_greedy_1_t1=time()

fair_kemeny_rankings_greedy_0_t0=time()
fair_kemeny_rankings_greedy_0=mc.fair_kemeny_mc_rankings_greedy(rankings,attribute,groups,threshold,0)
fair_kemeny_rankings_greedy_0_t1=time()

#fair_kemeny_rankings_greedy_1_t1-fair_kemeny_rankings_greedy_1_t0,
fair_kemeny_rankings_greedy_0_t1-fair_kemeny_rankings_greedy_0_t0

initial: 31


0.3380312919616699

In [17]:
fair_kemeny_rankings_greedy_1,fair_kemeny_rankings_greedy_0

NameError: name 'fair_kemeny_rankings_greedy_1' is not defined

In [ ]:


fair_kemeny_ranking_dist_greedy=np.array([row[1] for row in fair_kemeny_rankings_greedy_1])

optimal_fair_kemeny_ranking_greedy_1_index=np.argmin(fair_kemeny_ranking_dist_greedy)
optimal_fair_kemeny_ranking_greedy_1=fair_kemeny_rankings_greedy_1[optimal_fair_kemeny_ranking_greedy_1_index]
optimal_fair_kemeny_ranking_greedy_1_permutation=np.argsort(optimal_fair_kemeny_ranking_greedy_1[0])
optimal_fair_kemeny_ranking_greedy_1_permutation,optimal_fair_kemeny_ranking_greedy_1

In [18]:
fair_kemeny_ranking_dist_greedy=np.array([row[1] for row in fair_kemeny_rankings_greedy_0])

optimal_fair_kemeny_ranking_greedy_0_index=np.argmin(fair_kemeny_ranking_dist_greedy)
optimal_fair_kemeny_ranking_greedy_0=fair_kemeny_rankings_greedy_0[optimal_fair_kemeny_ranking_greedy_0_index]
optimal_fair_kemeny_ranking_greedy_0_permutation=np.argsort(optimal_fair_kemeny_ranking_greedy_0[0])
optimal_fair_kemeny_ranking_greedy_0_permutation,optimal_fair_kemeny_ranking_greedy_0

(array([31, 47, 30,  1, 45, 46, 10, 40, 43, 11, 42, 34, 48,  3, 55, 44,  4,
        52, 38, 20, 60, 32,  2, 50, 53, 58, 12, 63, 49,  8, 51, 54, 57,  9,
        62, 69, 24, 36, 39,  7, 73, 37, 56, 14, 64, 66,  6, 76, 35,  5, 70,
        65, 61, 16, 33, 41, 13,  0, 77, 80, 81, 86, 89, 29, 93, 72, 19, 78,
        68, 26, 74, 75, 92, 21, 67, 84, 17, 94, 82, 23, 91, 79, 88, 18, 59,
        83, 25, 99, 95, 22, 98, 85, 96, 28, 90, 15, 87, 71, 97, 27],
       dtype=int64),
 (array([57.,  3., 22., 13., 16., 49., 46., 39., 29., 33.,  6.,  9., 26.,
         56., 43., 95., 53., 76., 83., 66., 19., 73., 89., 79., 36., 86.,
         69., 99., 93., 63.,  2.,  0., 21., 54., 11., 48., 37., 41., 18.,
         38.,  7., 55., 10.,  8., 15.,  4.,  5.,  1., 12., 28., 23., 30.,
         17., 24., 31., 14., 42., 32., 25., 84., 20., 52., 34., 27., 44.,
         51., 45., 74., 68., 35., 50., 97., 65., 40., 70., 71., 47., 58.,
         67., 81., 59., 60., 78., 85., 75., 91., 61., 96., 82., 62., 94.,
         80.

In [11]:
optimal_fair_kemeny_ranking_greedy_1_m=np.c_[np.arange(30),optimal_fair_kemeny_ranking_greedy_1[0][:30]]
optimal_fair_kemeny_ranking_greedy_1_w=np.c_[np.arange(30,100),optimal_fair_kemeny_ranking_greedy_1[0][30:]]
parity_optimal_fair_kemeny_ranking_greedy_1=metrics.pairwise_statistical_parity(optimal_fair_kemeny_ranking_greedy_1_m,optimal_fair_kemeny_ranking_greedy_1_w)
parity_optimal_fair_kemeny_ranking_greedy_1

NameError: name 'optimal_fair_kemeny_ranking_greedy_1' is not defined

In [12]:
optimal_fair_kemeny_ranking_greedy_0_m=np.c_[np.arange(30),optimal_fair_kemeny_ranking_greedy_0[0][:30]]
optimal_fair_kemeny_ranking_greedy_0_w=np.c_[np.arange(30,100),optimal_fair_kemeny_ranking_greedy_0[0][30:]]
parity_optimal_fair_kemeny_ranking_greedy_0=metrics.pairwise_statistical_parity(optimal_fair_kemeny_ranking_greedy_0_m,optimal_fair_kemeny_ranking_greedy_0_w)
parity_optimal_fair_kemeny_ranking_greedy_0

NameError: name 'optimal_fair_kemeny_ranking_greedy_0' is not defined

In [13]:
satisfied_array=[]
k_threshold=0.05
for k in range(1,100):
    ranking =pd.DataFrame(columns=['id', 'ranker'])
    ranking["id"]=np.arange(0,100,1)
    ranking["ranker"]=optimal_fair_kemeny_ranking_greedy_1[0]
    ranking_m =ranking.head(30).to_numpy()
    ranking_w =ranking.tail(70).to_numpy()
    rankings_fair=np.array([ranking_m,ranking_w], dtype=object)
    satisfied=metrics.top_k_parity(rankings_fair,k,k-threshold )
    satisfied_array.append(["ranker",k,satisfied])

NameError: name 'optimal_fair_kemeny_ranking_greedy_1' is not defined

In [14]:
satisfied_array=np.array(satisfied_array)
satisfied_array

array([], dtype=float64)

In [15]:
satisfied_array=[]
for k in range(1,100):
    ranking =pd.DataFrame(columns=['id', 'ranker'])
    ranking["id"]=np.arange(0,100,1)
    ranking["ranker"]=optimal_fair_kemeny_ranking_greedy_0[0]
    ranking_m =ranking.head(30).to_numpy()
    ranking_w =ranking.tail(70).to_numpy()
    rankings_fair=np.array([ranking_m,ranking_w], dtype=object)
    satisfied=metrics.top_k_parity(rankings_fair,k,threshold )
    satisfied_array.append(["ranker",k,satisfied])

NameError: name 'optimal_fair_kemeny_ranking_greedy_0' is not defined

In [16]:
satisfied_array=np.array(satisfied_array)
satisfied_array

array([], dtype=float64)

In [10]:

t0=time()
agg_ranking_0=mc.aggregate_rank_mc(rankings,0)
t1=time()
agg_ranking_1=mc.aggregate_rank_mc(rankings,1)
agg_ranking_0,t1-t0,agg_ranking_1

[0.55083333 0.00333333 0.00333333 0.0025     0.0025     0.0025
 0.0025     0.00333333 0.00333333 0.0025     0.00416667 0.00333333
 0.00333333 0.0025     0.00333333 0.00333333 0.00333333 0.0025
 0.00166667 0.0025     0.005      0.00333333 0.00083333 0.0025
 0.00333333 0.00333333 0.005      0.00166667 0.0025     0.00333333
 0.005      0.00666667 0.005      0.00333333 0.005      0.00333333
 0.00416667 0.00416667 0.00333333 0.005      0.005      0.00333333
 0.00583333 0.005      0.00666667 0.0075     0.00583333 0.0075
 0.00583333 0.00416667 0.005      0.005      0.00583333 0.00583333
 0.005      0.00666667 0.005      0.005      0.00583333 0.00333333
 0.00666667 0.005      0.005      0.005      0.005      0.005
 0.00666667 0.005      0.005      0.00666667 0.00583333 0.00333333
 0.005      0.00583333 0.005      0.00416667 0.00583333 0.005
 0.005      0.00416667 0.005      0.00583333 0.005      0.005
 0.00583333 0.005      0.005      0.005      0.005      0.00583333
 0.00416667 0.005      0.0

(array([31, 15, 17, 36, 34, 52, 57, 42, 48, 43, 18, 28, 39, 76, 51, 90, 79,
        89, 97, 93, 29, 70, 95, 72, 49, 88, 63, 94, 92, 64,  3,  0, 14, 35,
         7, 32, 21, 27, 11, 26,  5, 50,  8,  4,  9,  2,  6,  1, 12, 25, 23,
        30, 13, 22, 24, 10, 47, 37, 20, 84, 16, 53, 41, 19, 46, 56, 44, 83,
        73, 33, 45, 99, 74, 40, 69, 67, 38, 65, 77, 80, 59, 58, 75, 86, 78,
        87, 62, 96, 81, 55, 91, 66, 61, 54, 60, 71, 85, 98, 82, 68],
       dtype=int64),
 0.10801053047180176,
 array([46, 20, 16, 44, 43, 73, 72, 65, 56, 68, 33, 39, 47, 84, 64, 86, 82,
        91, 95, 92, 45, 90, 96, 93, 66, 97, 89, 99, 98, 88,  1,  0, 15, 42,
         8, 36, 26, 32, 13, 28,  4, 48,  7,  6, 10,  3,  5,  2,  9, 22, 19,
        24, 12, 17, 23, 11, 31, 25, 18, 75, 14, 41, 27, 21, 34, 40, 35, 61,
        53, 29, 38, 87, 55, 30, 59, 60, 37, 50, 54, 71, 51, 49, 69, 77, 63,
        79, 52, 85, 74, 58, 83, 70, 62, 57, 67, 78, 81, 94, 80, 76],
       dtype=int64))

In [11]:
agg_ranking_permutation_0=np.argsort(agg_ranking_0)
agg_ranking_permutation_1=np.argsort(agg_ranking_1)
agg_ranking_permutation_0,agg_ranking_permutation_1,ul.kemeny_dist(rankings,agg_ranking_0),ul.kemeny_dist(rankings,agg_ranking_1)

(array([31, 47, 45, 30, 43, 40, 46, 34, 42, 44, 55, 38, 48, 52, 32,  1, 60,
         2, 10, 63, 58, 36, 53, 50, 54, 49, 39, 37, 11, 20, 51,  0, 35, 69,
         4, 33,  3, 57, 76, 12, 73, 62,  7,  9, 66, 70, 64, 56,  8, 24, 41,
        14,  5, 61, 93, 89, 65,  6, 81, 80, 94, 92, 86, 26, 29, 77, 91, 75,
        99, 74, 21, 95, 23, 68, 72, 82, 13, 78, 84, 16, 79, 88, 98, 67, 59,
        96, 83, 85, 25, 17, 15, 90, 28, 19, 27, 22, 87, 18, 97, 71],
       dtype=int64),
 array([31, 30, 47, 45, 40, 46, 43, 42, 34, 48, 44, 55, 52, 38, 60, 32,  2,
        53, 58, 50,  1, 63, 49, 54, 51, 57, 36, 62, 39, 69, 73, 56, 37, 10,
        64, 66, 35, 76, 70, 11, 65, 61, 33,  4,  3, 20,  0, 12, 41, 81, 77,
        80, 86, 68, 78, 72,  8, 93, 89, 74, 75, 67, 92, 84, 14,  7, 24, 94,
         9, 82, 91, 79,  6,  5, 88, 59, 99, 83, 95, 85, 98, 96, 16, 90, 13,
        87, 15, 71, 29, 26, 21, 17, 19, 23, 97, 18, 22, 25, 28, 27],
       dtype=int64),
 22356,
 21962)

In [12]:
fair_agg_ranking_permutation_0=ul.GrBinaryIPF(agg_ranking_permutation_0,attribute[:,1])
fair_agg_ranking_0=np.zeros(len(fair_agg_ranking_permutation_0))
for i in range(len(fair_agg_ranking_permutation_0)):
    fair_agg_ranking_0[fair_agg_ranking_permutation_0[i]]=i
fair_agg_ranking_permutation_0,fair_agg_ranking_0

[]
[31]
[31, 47]
[31, 47, 45]
[31, 47, 45, 1]
[31, 47, 45, 1, 30]
[31, 47, 45, 1, 30, 43]
[31, 47, 45, 1, 30, 43, 2]
[31, 47, 45, 1, 30, 43, 2, 40]
[31, 47, 45, 1, 30, 43, 2, 40, 46]
[31, 47, 45, 1, 30, 43, 2, 40, 46, 10]
[31, 47, 45, 1, 30, 43, 2, 40, 46, 10, 34]
[31, 47, 45, 1, 30, 43, 2, 40, 46, 10, 34, 42]
[31, 47, 45, 1, 30, 43, 2, 40, 46, 10, 34, 42, 44]
[31, 47, 45, 1, 30, 43, 2, 40, 46, 10, 34, 42, 44, 11]
[31, 47, 45, 1, 30, 43, 2, 40, 46, 10, 34, 42, 44, 11, 55]
[31, 47, 45, 1, 30, 43, 2, 40, 46, 10, 34, 42, 44, 11, 55, 38]
[31, 47, 45, 1, 30, 43, 2, 40, 46, 10, 34, 42, 44, 11, 55, 38, 20]
[31, 47, 45, 1, 30, 43, 2, 40, 46, 10, 34, 42, 44, 11, 55, 38, 20, 48]
[31, 47, 45, 1, 30, 43, 2, 40, 46, 10, 34, 42, 44, 11, 55, 38, 20, 48, 52]
[31, 47, 45, 1, 30, 43, 2, 40, 46, 10, 34, 42, 44, 11, 55, 38, 20, 48, 52, 0]
[31, 47, 45, 1, 30, 43, 2, 40, 46, 10, 34, 42, 44, 11, 55, 38, 20, 48, 52, 0, 32]
[31, 47, 45, 1, 30, 43, 2, 40, 46, 10, 34, 42, 44, 11, 55, 38, 20, 48, 52, 0, 32, 60]
[

([31,
  47,
  45,
  1,
  30,
  43,
  2,
  40,
  46,
  10,
  34,
  42,
  44,
  11,
  55,
  38,
  20,
  48,
  52,
  0,
  32,
  60,
  63,
  4,
  58,
  36,
  3,
  53,
  50,
  12,
  54,
  49,
  39,
  7,
  37,
  51,
  9,
  35,
  69,
  8,
  33,
  57,
  76,
  24,
  73,
  62,
  14,
  66,
  70,
  5,
  64,
  56,
  41,
  6,
  61,
  93,
  26,
  89,
  65,
  29,
  81,
  80,
  94,
  21,
  92,
  86,
  23,
  77,
  91,
  13,
  75,
  99,
  74,
  16,
  95,
  68,
  25,
  72,
  82,
  17,
  78,
  84,
  79,
  15,
  88,
  98,
  28,
  67,
  59,
  19,
  96,
  83,
  85,
  27,
  90,
  22,
  87,
  18,
  97,
  71],
 array([19.,  3.,  6., 26., 23., 49., 53., 33., 39., 36.,  9., 13., 29.,
        69., 46., 83., 73., 79., 97., 89., 16., 63., 95., 66., 43., 76.,
        56., 93., 86., 59.,  4.,  0., 20., 40., 10., 37., 25., 34., 15.,
        32.,  7., 52., 11.,  5., 12.,  2.,  8.,  1., 17., 31., 28., 35.,
        18., 27., 30., 14., 51., 41., 24., 88., 21., 54., 45., 22., 50.,
        58., 47., 87., 75., 38., 48., 99., 7

In [13]:
fair_agg_ranking_permutation_1=ul.GrBinaryIPF(agg_ranking_permutation_1,attribute[:,1])
fair_agg_ranking_1=np.zeros(len(fair_agg_ranking_permutation_1))
for i in range(len(fair_agg_ranking_permutation_1)):
    fair_agg_ranking_1[fair_agg_ranking_permutation_1[i]]=i
fair_agg_ranking_permutation_1,fair_agg_ranking_1

[]
[31]
[31, 30]
[31, 30, 47]
[31, 30, 47, 2]
[31, 30, 47, 2, 45]
[31, 30, 47, 2, 45, 40]
[31, 30, 47, 2, 45, 40, 1]
[31, 30, 47, 2, 45, 40, 1, 46]
[31, 30, 47, 2, 45, 40, 1, 46, 43]
[31, 30, 47, 2, 45, 40, 1, 46, 43, 10]
[31, 30, 47, 2, 45, 40, 1, 46, 43, 10, 42]
[31, 30, 47, 2, 45, 40, 1, 46, 43, 10, 42, 34]
[31, 30, 47, 2, 45, 40, 1, 46, 43, 10, 42, 34, 48]
[31, 30, 47, 2, 45, 40, 1, 46, 43, 10, 42, 34, 48, 11]
[31, 30, 47, 2, 45, 40, 1, 46, 43, 10, 42, 34, 48, 11, 44]
[31, 30, 47, 2, 45, 40, 1, 46, 43, 10, 42, 34, 48, 11, 44, 55]
[31, 30, 47, 2, 45, 40, 1, 46, 43, 10, 42, 34, 48, 11, 44, 55, 4]
[31, 30, 47, 2, 45, 40, 1, 46, 43, 10, 42, 34, 48, 11, 44, 55, 4, 52]
[31, 30, 47, 2, 45, 40, 1, 46, 43, 10, 42, 34, 48, 11, 44, 55, 4, 52, 38]
[31, 30, 47, 2, 45, 40, 1, 46, 43, 10, 42, 34, 48, 11, 44, 55, 4, 52, 38, 3]
[31, 30, 47, 2, 45, 40, 1, 46, 43, 10, 42, 34, 48, 11, 44, 55, 4, 52, 38, 3, 60]
[31, 30, 47, 2, 45, 40, 1, 46, 43, 10, 42, 34, 48, 11, 44, 55, 4, 52, 38, 3, 60, 32]
[31, 30

([31,
  30,
  47,
  2,
  45,
  40,
  1,
  46,
  43,
  10,
  42,
  34,
  48,
  11,
  44,
  55,
  4,
  52,
  38,
  3,
  60,
  32,
  53,
  20,
  58,
  50,
  0,
  63,
  49,
  12,
  54,
  51,
  57,
  8,
  36,
  62,
  14,
  39,
  69,
  7,
  73,
  56,
  37,
  24,
  64,
  66,
  9,
  35,
  76,
  6,
  70,
  65,
  61,
  5,
  33,
  41,
  16,
  81,
  77,
  13,
  80,
  86,
  68,
  15,
  78,
  72,
  29,
  93,
  89,
  26,
  74,
  75,
  67,
  21,
  92,
  84,
  17,
  94,
  82,
  19,
  91,
  79,
  88,
  23,
  59,
  99,
  18,
  83,
  95,
  22,
  85,
  98,
  96,
  25,
  90,
  87,
  28,
  71,
  97,
  27],
 array([26.,  6.,  3., 19., 16., 53., 49., 39., 33., 46.,  9., 13., 29.,
        59., 36., 63., 56., 76., 86., 79., 23., 73., 89., 83., 43., 93.,
        69., 99., 96., 66.,  1.,  0., 21., 54., 11., 47., 34., 42., 18.,
        37.,  5., 55., 10.,  8., 14.,  4.,  7.,  2., 12., 28., 25., 31.,
        17., 22., 30., 15., 41., 32., 24., 84., 20., 52., 35., 27., 44.,
        51., 45., 72., 62., 38., 50., 97., 6

In [14]:
fair_agg_ranking_distance_0=ul.kemeny_dist(rankings,fair_agg_ranking_0)
fair_agg_ranking_distance_0

22568

In [15]:
fair_agg_ranking_distance_1=ul.kemeny_dist(rankings,fair_agg_ranking_1)
fair_agg_ranking_distance_1

22472

In [88]:
fair_agg_ranking_0_m=np.c_[np.arange(30),fair_agg_ranking_0[:30]]
fair_agg_ranking_0_w=np.c_[np.arange(30,100),fair_agg_ranking_0[30:]]
parity_fair_agg_ranking_0=metrics.pairwise_statistical_parity(fair_agg_ranking_0_m,fair_agg_ranking_0_w)
parity_fair_agg_ranking_0

0.04380952380952381

In [89]:
fair_agg_ranking_1_m=np.c_[np.arange(30),fair_agg_ranking_1[:30]]
fair_agg_ranking_1_w=np.c_[np.arange(30,100),fair_agg_ranking_1[30:]]
parity_fair_agg_ranking_1=metrics.pairwise_statistical_parity(fair_agg_ranking_1_m,fair_agg_ranking_1_w)
parity_fair_agg_ranking_1

-0.04285714285714286

In [90]:
agg_ranking_0_satisfied_array=[]
k_threshold=threshold
for k in range(1,100):
    agg_ranking_0_k =pd.DataFrame(columns=['id', 'ranker'])
    agg_ranking_0_k["id"]=np.arange(0,100,1)
    agg_ranking_0_k["ranker"]=agg_ranking_0
    agg_ranking_0_k_m =agg_ranking_0_k.head(30).to_numpy()
    agg_ranking_0_k_w =agg_ranking_0_k.tail(70).to_numpy()
    agg_ranking_0_k_groups=np.array([agg_ranking_0_k_m,agg_ranking_0_k_w], dtype=object)
    agg_ranking_0_k_satisfied=metrics.top_k_parity(agg_ranking_0_k_groups,k,k_threshold )
    print(["ranker",k,agg_ranking_0_k_satisfied])
    agg_ranking_0_satisfied_array.append(["ranker",k,agg_ranking_0_k_satisfied])


['ranker', 1, True]
['ranker', 2, False]
['ranker', 3, False]
['ranker', 4, False]
['ranker', 5, False]
['ranker', 6, False]
['ranker', 7, False]
['ranker', 8, False]
['ranker', 9, False]
['ranker', 10, False]
['ranker', 11, False]
['ranker', 12, False]
['ranker', 13, False]
['ranker', 14, False]
['ranker', 15, False]
['ranker', 16, False]
['ranker', 17, False]
['ranker', 18, False]
['ranker', 19, False]
['ranker', 20, False]
['ranker', 21, False]
['ranker', 22, False]
['ranker', 23, False]
['ranker', 24, False]
['ranker', 25, False]
['ranker', 26, False]
['ranker', 27, False]
['ranker', 28, False]
['ranker', 29, False]
['ranker', 30, False]
['ranker', 31, False]
['ranker', 32, False]
['ranker', 33, False]
['ranker', 34, False]
['ranker', 35, False]
['ranker', 36, False]
['ranker', 37, False]
['ranker', 38, False]
['ranker', 39, False]
['ranker', 40, False]
['ranker', 41, False]
['ranker', 42, False]
['ranker', 43, False]
['ranker', 44, False]
['ranker', 45, False]
['ranker', 46, False

In [91]:
agg_ranking_0_satisfied_array

[['ranker', 1, True],
 ['ranker', 2, False],
 ['ranker', 3, False],
 ['ranker', 4, False],
 ['ranker', 5, False],
 ['ranker', 6, False],
 ['ranker', 7, False],
 ['ranker', 8, False],
 ['ranker', 9, False],
 ['ranker', 10, False],
 ['ranker', 11, False],
 ['ranker', 12, False],
 ['ranker', 13, False],
 ['ranker', 14, False],
 ['ranker', 15, False],
 ['ranker', 16, False],
 ['ranker', 17, False],
 ['ranker', 18, False],
 ['ranker', 19, False],
 ['ranker', 20, False],
 ['ranker', 21, False],
 ['ranker', 22, False],
 ['ranker', 23, False],
 ['ranker', 24, False],
 ['ranker', 25, False],
 ['ranker', 26, False],
 ['ranker', 27, False],
 ['ranker', 28, False],
 ['ranker', 29, False],
 ['ranker', 30, False],
 ['ranker', 31, False],
 ['ranker', 32, False],
 ['ranker', 33, False],
 ['ranker', 34, False],
 ['ranker', 35, False],
 ['ranker', 36, False],
 ['ranker', 37, False],
 ['ranker', 38, False],
 ['ranker', 39, False],
 ['ranker', 40, False],
 ['ranker', 41, False],
 ['ranker', 42, False],
 [

In [92]:
t0=time()
kemeny_dist_0=ul.kemeny_dist(rankings,agg_ranking_0)
##kemeny_dist_1=ul.kemeny_dist(rankings,agg_ranking_1)

kemeny_dist_0,#kemeny_dist_1

(37124,)

In [17]:
ranking_mc_0_m=np.c_[np.arange(30),agg_ranking_0[:30]]
ranking_mc_0_w=np.c_[np.arange(30,100),agg_ranking_0[30:]]
#ranking_mc_1_m=np.c_[np.arange(30),agg_ranking_1[:30]]
#ranking_mc_1_w=np.c_[np.arange(30,100),agg_ranking_1[30:]]
ranking_mc_0_m,ranking_mc_0_w,#ranking_mc_1_m,#ranking_mc_1_w

NameError: name 'agg_ranking_0' is not defined

In [24]:


parity_mc_0=metrics.pairwise_statistical_parity(ranking_mc_0_m,ranking_mc_0_w)
parity_mc_0,

(-0.38285714285714284,)

In [8]:
n_voter,n_candidate=rankings.shape

In [26]:
kemeny_ranking=ul.aggregate_kemeny(n_voter,n_candidate,rankings)

Set parameter Username
Academic license - for non-commercial use only - expires 2024-11-13
1
2
3
4
5


In [27]:

kemeny_ranking_gurobi=kemeny_ranking
kemeny_ranking_gurobi

(array([68.,  0.,  2., 73., 75., 76., 77., 78., 79., 80.,  4.,  5., 81.,
        82., 83., 85., 86., 87., 88., 89.,  6., 90., 91., 92., 93., 94.,
        95., 96., 97., 98.,  1.,  3.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 22., 16., 17., 18., 19., 20., 21., 23., 24., 25., 26.,
        27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
        40., 41., 42., 43., 44., 45., 99., 46., 47., 48., 49., 50., 51.,
        52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
        65., 66., 67., 69., 70., 71., 84., 72., 74.]),
 10.413635492324829)

In [28]:
kemeny_dist_gurobi=ul.kemeny_dist(rankings,kemeny_ranking[0])
kemeny_dist_gurobi

20680

In [29]:
kemeny_ranking_gurobi_m=np.c_[np.arange(30),kemeny_ranking_gurobi[0][:30]]
kemeny_ranking_gurobi_w=np.c_[np.arange(30,100),kemeny_ranking_gurobi[0][30:]]
parity_kemeny_ranking_gurobi=metrics.pairwise_statistical_parity(kemeny_ranking_gurobi_m,kemeny_ranking_gurobi_w)
parity_kemeny_ranking_gurobi

-0.6333333333333333

In [9]:
fair_kemeny_ranking_gurobi_attribute=attribute[:,1]
fair_kemeny_ranking_gurobi_attribute[1]-fair_kemeny_ranking_gurobi_attribute[50],type(fair_kemeny_ranking_gurobi_attribute[0])

(-1, numpy.int32)

In [10]:
fair_kemeny_ranking_gurobi=ul.aggregate_parity(n_voter,n_candidate,rankings,fair_kemeny_ranking_gurobi_attribute,threshold)

Set parameter Username
Academic license - for non-commercial use only - expires 2024-11-13


In [12]:
fair_kemeny_ranking_gurobi

(array([ 3.,  4.,  5.,  6.,  7.,  8., 82.,  9., 10., 11., 12., 13., 14.,
        83., 16., 84., 85., 86., 87., 88., 15., 89., 90., 91., 17., 92.,
        93., 94., 95., 96., 18.,  0., 19., 21., 20., 22., 23., 24., 25.,
        26., 27., 28., 29., 30., 31.,  1., 32.,  2., 33., 34., 35., 36.,
        37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.,
        50., 51., 52., 53., 54., 55., 97., 56., 57., 58., 60., 59., 61.,
        62., 63., 64., 65., 66., 67., 68., 69., 70., 98., 71., 72., 73.,
        74., 75., 76., 77., 78., 79., 99., 80., 81.]),
 127.11997652053833)

In [13]:
optimal_fair_kemeny_ranking_gurobi_permutation=np.argsort(fair_kemeny_ranking_gurobi[0])
fair_kemeny_ranking_gurobi,optimal_fair_kemeny_ranking_gurobi_permutation

((array([ 3.,  4.,  5.,  6.,  7.,  8., 82.,  9., 10., 11., 12., 13., 14.,
         83., 16., 84., 85., 86., 87., 88., 15., 89., 90., 91., 17., 92.,
         93., 94., 95., 96., 18.,  0., 19., 21., 20., 22., 23., 24., 25.,
         26., 27., 28., 29., 30., 31.,  1., 32.,  2., 33., 34., 35., 36.,
         37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.,
         50., 51., 52., 53., 54., 55., 97., 56., 57., 58., 60., 59., 61.,
         62., 63., 64., 65., 66., 67., 68., 69., 70., 98., 71., 72., 73.,
         74., 75., 76., 77., 78., 79., 99., 80., 81.]),
  127.11997652053833),
 array([31, 45, 47,  0,  1,  2,  3,  4,  5,  7,  8,  9, 10, 11, 12, 20, 14,
        24, 30, 32, 34, 33, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 46, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 72, 73, 74, 76, 75, 77, 78, 79, 80, 81, 82, 83,
        84, 85, 86, 88, 89, 90, 91, 92, 93, 94, 95, 96, 98, 99,  6, 13, 15,
        16, 17, 18, 19,

In [14]:
fair_kemeny_dist_gurobi=ul.kemeny_dist(rankings,fair_kemeny_ranking_gurobi[0])

In [15]:
fair_kemeny_dist_gurobi

21060

In [16]:
fair_kemeny_ranking_gurobi_m=np.c_[np.arange(30),fair_kemeny_ranking_gurobi[0][:30]]
fair_kemeny_ranking_gurobi_w=np.c_[np.arange(30,100),fair_kemeny_ranking_gurobi[0][30:]]

In [17]:
fair_kemeny_ranking_gurobi_w,fair_kemeny_ranking_gurobi_m

(array([[30., 18.],
        [31.,  0.],
        [32., 19.],
        [33., 21.],
        [34., 20.],
        [35., 22.],
        [36., 23.],
        [37., 24.],
        [38., 25.],
        [39., 26.],
        [40., 27.],
        [41., 28.],
        [42., 29.],
        [43., 30.],
        [44., 31.],
        [45.,  1.],
        [46., 32.],
        [47.,  2.],
        [48., 33.],
        [49., 34.],
        [50., 35.],
        [51., 36.],
        [52., 37.],
        [53., 38.],
        [54., 39.],
        [55., 40.],
        [56., 41.],
        [57., 42.],
        [58., 43.],
        [59., 44.],
        [60., 45.],
        [61., 46.],
        [62., 47.],
        [63., 48.],
        [64., 49.],
        [65., 50.],
        [66., 51.],
        [67., 52.],
        [68., 53.],
        [69., 54.],
        [70., 55.],
        [71., 97.],
        [72., 56.],
        [73., 57.],
        [74., 58.],
        [75., 60.],
        [76., 59.],
        [77., 61.],
        [78., 62.],
        [79., 63.],


In [18]:
parity_fair_kemeny_ranking_gurobi=metrics.pairwise_statistical_parity(fair_kemeny_ranking_gurobi_m,fair_kemeny_ranking_gurobi_w)

In [19]:
parity_fair_kemeny_ranking_gurobi

0.0

In [22]:
fair_kemeny_ranking_gurobi_satisfied_array=[]
k_threshold=0.05
for k in range(1,100):
    fair_kemeny_ranking_gurobi_k =pd.DataFrame(columns=['id', 'ranker'])
    fair_kemeny_ranking_gurobi_k["id"]=np.arange(0,100,1)
    fair_kemeny_ranking_gurobi_k["ranker"]=fair_kemeny_ranking_gurobi[0]
    fair_kemeny_ranking_gurobi_k_m =fair_kemeny_ranking_gurobi_k.head(30).to_numpy()
    fair_kemeny_ranking_gurobi_k_w =fair_kemeny_ranking_gurobi_k.tail(70).to_numpy()
    fair_kemeny_ranking_gurobi_k_groups=np.array([fair_kemeny_ranking_gurobi_k_m,fair_kemeny_ranking_gurobi_k_w], dtype=object)
    fair_kemeny_ranking_gurobi_k_satisfied=metrics.top_k_parity(fair_kemeny_ranking_gurobi_k_groups,k,k_threshold )
    fair_kemeny_ranking_gurobi_satisfied_array.append(["ranker",k,fair_kemeny_ranking_gurobi_k_satisfied])

In [23]:
fair_kemeny_ranking_gurobi_satisfied_array

[['ranker', 1, True],
 ['ranker', 2, True],
 ['ranker', 3, True],
 ['ranker', 4, True],
 ['ranker', 5, True],
 ['ranker', 6, True],
 ['ranker', 7, False],
 ['ranker', 8, False],
 ['ranker', 9, False],
 ['ranker', 10, False],
 ['ranker', 11, False],
 ['ranker', 12, False],
 ['ranker', 13, False],
 ['ranker', 14, False],
 ['ranker', 15, False],
 ['ranker', 16, False],
 ['ranker', 17, False],
 ['ranker', 18, False],
 ['ranker', 19, False],
 ['ranker', 20, False],
 ['ranker', 21, False],
 ['ranker', 22, False],
 ['ranker', 23, False],
 ['ranker', 24, False],
 ['ranker', 25, False],
 ['ranker', 26, False],
 ['ranker', 27, False],
 ['ranker', 28, False],
 ['ranker', 29, False],
 ['ranker', 30, False],
 ['ranker', 31, False],
 ['ranker', 32, False],
 ['ranker', 33, False],
 ['ranker', 34, False],
 ['ranker', 35, False],
 ['ranker', 36, False],
 ['ranker', 37, False],
 ['ranker', 38, False],
 ['ranker', 39, False],
 ['ranker', 40, False],
 ['ranker', 41, True],
 ['ranker', 42, True],
 ['ranker

In [33]:
stationary_distribute_0 = mc.stationary_distribute(rankings, 0)
stationary_distribute_1 = mc.stationary_distribute(rankings, 1)
stationary_distribute_0, stationary_distribute_1

(array([0.00636478-0.j, 0.00445895-0.j, 0.00433305-0.j, 0.00697691-0.j,
        0.00678303-0.j, 0.00819253-0.j, 0.0091479 -0.j, 0.00723867-0.j,
        0.00742216-0.j, 0.00737572-0.j, 0.00498958-0.j, 0.00547314-0.j,
        0.00618114-0.j, 0.01109269-0.j, 0.00715125-0.j, 0.01399296-0.j,
        0.01099729-0.j, 0.01370725-0.j, 0.0187458 -0.j, 0.01531436-0.j,
        0.00533095-0.j, 0.01035163-0.j, 0.01732745-0.j, 0.0101525 -0.j,
        0.00683577-0.j, 0.01337098-0.j, 0.00865876-0.j, 0.01760905-0.j,
        0.0135678 -0.j, 0.00888645-0.j, 0.0049487 -0.j, 0.00411924-0.j,
        0.00809632-0.j, 0.01246436-0.j, 0.00627435-0.j, 0.01102661-0.j,
        0.00971973-0.j, 0.0098939 -0.j, 0.0066931 -0.j, 0.00979832-0.j,
        0.00565976-0.j, 0.01319912-0.j, 0.00582666-0.j, 0.00497843-0.j,
        0.00582702-0.j, 0.00386067-0.j, 0.00503643-0.j, 0.00339434-0.j,
        0.00583961-0.j, 0.00777182-0.j, 0.00772563-0.j, 0.00823878-0.j,
        0.00590396-0.j, 0.00743119-0.j, 0.00737774-0.j, 0.005144

In [34]:
transition_matrix_0 = mc.generate_transition_matrix(rankings)
transition_matrix_1 = mc.generate_transition_matrix_without_self_circle(rankings)
#sum_of_probability_candidate=np.array([np.sum(transition_matrix_2[i, :]) for i in range(rankings.shape[1])])

transition_matrix_0[30],transition_matrix_1[30]

(array([0.004, 0.003, 0.005, 0.006, 0.005, 0.005, 0.005, 0.004, 0.005,
        0.005, 0.003, 0.004, 0.004, 0.005, 0.005, 0.008, 0.005, 0.006,
        0.007, 0.006, 0.004, 0.005, 0.008, 0.006, 0.005, 0.006, 0.005,
        0.007, 0.007, 0.005, 0.357, 0.005, 0.006, 0.009, 0.006, 0.009,
        0.008, 0.009, 0.007, 0.007, 0.006, 0.01 , 0.006, 0.007, 0.007,
        0.004, 0.005, 0.006, 0.007, 0.007, 0.008, 0.006, 0.006, 0.008,
        0.007, 0.006, 0.007, 0.008, 0.007, 0.007, 0.007, 0.008, 0.008,
        0.007, 0.008, 0.007, 0.007, 0.008, 0.008, 0.005, 0.006, 0.008,
        0.007, 0.008, 0.007, 0.007, 0.006, 0.006, 0.008, 0.007, 0.007,
        0.007, 0.008, 0.008, 0.007, 0.007, 0.006, 0.008, 0.008, 0.006,
        0.008, 0.007, 0.006, 0.005, 0.007, 0.007, 0.007, 0.008, 0.007,
        0.007]),
 array([0.00622084, 0.00466563, 0.00777605, 0.00933126, 0.00777605,
        0.00777605, 0.00777605, 0.00622084, 0.00777605, 0.00777605,
        0.00466563, 0.00622084, 0.00622084, 0.00777605, 0.00777605